### ISSUE TITLE
FR: Substring replace multiple times

### ISSUE THREAD

**Issue by xyrolaith** [tumpio/requestcontrol#101]
The substring replace feature only matches the first occurence but most regular expression engines allow to specify a "global" modifier in order to match the string multiple times.

The only way to achieve this currently is to chain the same substring replace pattern as often as needed. This makes the action rather complex and may fail if the string occurs more often than anticipated.

**Comment by anewuser** [comment]
Give an example URL with the expected result.

**Comment by xyrolaith** [comment]
**URL:** http://track.steadyhq.com/track/click/12345678/steadyhq.com?p=eyJzIjoidDJLdmg0NVV4MUJkNFh3N3lrUkR6djRMWlJNIiwidiI6MSwicCI6IntcInVcIjoxMjM0NTY3OCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3N0ZWFkeWhxLmNvbVxcXC9wcm9qZWN0XFxcL3Bvc3RzXFxcLzlmYjYwMWU0LWIzMjctNGY2YS01NzljLWU1NGM4NDE1YmY0YlwiLFwiaWRcIjpcIjZmOTNmMTZhYWE0NTQyYjk2M2M2NjEwOGMwZTk4ZjJcIixcInVybF9pZHNcIjpbXCI2OWExOTZiYWIzODNmN2YyZDcxMDQxMjA3MWQ5NjhmNmRiYmVlMDQ4XCJdfSJ9

I basically take the string from the parameter **p** which is a Base64 encoded JSON object like this:

`{"s":"t2Kvh45Ux1Bd4Xw7ykRDzv4LZRM","v":1,"p":"{\"u\":12345678,\"v\":1,\"url\":\"https:\\\/\\\/steadyhq.com\\\/project\\\/posts\\\/9fb601e4-b327-4f6a-579c-e54c8415bf4b\",\"id\":\"6f93f16aaa4542b963c66108c0e98f2\",\"url_ids\":[\"69a196bab383f7f2d710412071d968f6dbbee048\"]}"}`

My action: `{search.p|decodeBase64|/.*\\"(https:.*)\\",\\"id.*/$1|/\\+/}`

- decode the base64 part
- use a simple regex to scrape out the target url resulting in:
`https:\\\/\\\/steadyhq.com\\\/project\\\/posts\\\/9fb601e4-b327-4f6a-579c-e54c8415bf4b`
- replace all backslashes (this should match all occurrences) but the result will be:
`https:/\\\/steadyhq.com\\\/project\\\/posts\\\/9fb601e4-b327-4f6a-579c-e54c8415bf4b`

As a workaround I simply repeat the last substring replace action multiple times to catch them all:
`{search.p|decodeBase64|/.*\\"(https:.*)\\",\\"id.*/$1|/\\+/|/\\+/|/\\+/|/\\+/|/\\+/|/\\+/|/\\+/}`
which will return the expected target URL:
https://steadyhq.com/project/posts/9fb601e4-b327-4f6a-579c-e54c8415bf4b

**Comment by tumpio** [comment]
This could be the default behaviour. If both methods are needed to be supported, this could be added as a flag (**g**) for substring replace pattern, like it is defined in javascript regexp patterns.

**Comment by xyrolaith** [comment]
A separate global flag might indeed be useful.

In my case on the other hand a _decodeJSON_ function with proper escaping would probably make more sense as my regexp is just an ugly hack to get the value of the **url** key.

**Comment by tumpio** [comment]
Added replace all substrings support in 1.13.0.
