### ISSUE TITLE
provide visual indication of cleaned redirect

### ISSUE THREAD

**Issue by atomGit** [tumpio/requestcontrol#11]
there seems to be no visual indication that the extension is working - for example, when clicking a URL from a Google search result, the redirect URL appears in the address bar before the destination URL loads, as if RC wasn't working at all

i had been using Clean Links and i very much liked that it provided a visual indication when it 'cleaned' a link by briefly changing the background color of the address bar and, optionally, by restyling the source link with CSS

**Comment by tumpio** [comment]
The visual indicator is displayed in url bar. Do you see that? It is the icon of the applied rule action (filter, block, redirect,..)

**Comment by atomGit** [comment]
ha! i missed that - sorry

**Comment by ldgbc** [comment]
#1 Just for reference.
