### ISSUE TITLE
Popup unusable when pinned to overflow menu

### ISSUE THREAD

**Issue by hackel** [tumpio/requestcontrol#111]
### Expected behavior
The Request Control popup should be usable even when it is pinned to the overflow menu.

### Actual behavior
The height is shrunk (proportional to the forced width perhaps?), making the popup unusable.
![image](https://user-images.githubusercontent.com/583677/71566834-6b252b80-2a80-11ea-9ce5-4a8622e8e0ec.png)

It seems like it just needs a more responsive layout that can use the full height of the overflow menu when the width is constrained to the menu width.

**Comment by geekyi** [comment]
This works for me on:
Firefox 75.0b2 (64-bit) Windows 10 64bit

I guess it's fixed now? Or needs more details..

**Comment by tumpio** [comment]
Found a work around for it. Could be that it has been fixed already in Firefox beta. The overflow menu seems to have quite many issues:
https://bugzilla.mozilla.org/show_bug.cgi?id=1459046

**Comment by tumpio** [comment]
Fixed in 1.15.1
