### ISSUE TITLE
Case sensitivity of host names

### ISSUE THREAD

**Issue by Gitoffthelawn** [tumpio/requestcontrol#116]
The [RC manual](https://github.com/tumpio/requestcontrol/blob/master/_locales/en/manual.wiki) states that host names are currently case sensitive.

If I'm reading [RFC4343](https://tools.ietf.org/html/rfc4343) (not a fun read) correctly, hosts resolved by DNS are not case sensitive.

Thus, could sites bypass Request Control if they just used mixed-case host names?

If so, can this be fixed?

**Comment by in4u** [comment]
I too was wondering about the same when reading the manual yesterday and then came across [this](https://github.com/tumpio/requestcontrol/issues/16#issuecomment-310498155) workaround. Not sure if anything has changed since then.

**Comment by tumpio** [comment]
The match pattern that is constructed matches case sensitively. I think Firefox resolves host names in lower case.
