### ISSUE TITLE
Is recursion supported?

### ISSUE THREAD

**Issue by Gitoffthelawn** [tumpio/requestcontrol#117]
Thank you for this wonderful extension.

I've read the manual, readme, and wiki pages (and made a few edits), but I don't see any mention of recursion.

Is recursion supported, and if so, is there anything special that needs to be done to enable it?

For example, let's say the browser gets directed to:

> https://www.badsite01.com/?url=www.manypossiblesites.com/?a=anything&b=https%3A%2F%2Fexample.com%0D%0A&c=anything

And you want to redirect to:
> http://www.manypossiblesites.com/?a=anything&b=https%3A%2F%2Fexample.com%0D%0A&c=anything

And iff manypossiblesites=badsite02, you want to redirect to:
> https://example.com

Otherwise you don't want to redirect again.

IOW, how does one get the output processed recursively to see if it matches any rules?

**Comment by tumpio** [comment]
If the same rule (or another rule) also applies to "http://www.manypossiblesites.com/?a=anything&b=https%3A%2F%2Fexample.com%0D%0A&c=anything", it will be redirected to "https://example.com", without request being send to "http://www.manypossiblesites.com/..".

But parsing the redirection url is not done recursively, as you can see from the output when testing rules.

**Comment by Gitoffthelawn** [comment]
Thanks!  I've only started reviewing the code, so I'm a ways off of understand everything.  Please bear with me, but I'm having challenges understanding what you just wrote.

This is what I understood from what you wrote:

If URL A matches any rule, it will generate URL B.  If URL B then matches any rule (including the one that URL A matched), it will generate URL C.  And this goes on and on until the output URL does not match any rules.

Do I understand correctly?

If so, we're on the same page (if not, please correct me!).

But then you said it doesn't operate recursively.  Although programmatically, it's technically possible to have a recursive function without using actual recursion, it sounds like what it's doing is basically recursive.

What am I not understanding?

**Comment by tumpio** [comment]
Yes, that is correct. Rules can be chained and one rule can apply again to its own output.

If URL A is a redirect url to URL B and URL B is also a redirect to URL C, then a **Filter** rule that is applied to URL A results to URL B and not directly to URL C. The same rule or another Filter rule has to match URL B to redirect it to URL C.

**Comment by EchoDev** [comment]
I have the following rules:
```

Rule 1: Filter utm_* and ref_* parameters
Pattern: All URLs
Type: Document
Action: Filter
Trimmed query parameters: utm_* ref_*


Rule 2: Redirect reddit urls to old.reddit.com
Pattern: *.reddit.com
Type: Document
Action: Redirect
Redirect rule: {href|/^.*reddit\.com/https://old.reddit.com}

Test URL:  https://www.reddit.com/r/uBlockOrigin/?utm_source=example
Expected output: https://old.reddit.com/r/uBlockOrigin/
Actual output: https://old.reddit.com/r/uBlockOrigin/?utm_source=example
```

Rule 2 (redirect) seems to override rule 1 (filter) always. If I disable rule 2, rule 1 is able to remove the utm parameter.

If I chain 2 different redirect rules and 1 filter rule, only 1 redirect rule is being applied. The second redirect rule and the filter get ignored.
