### ISSUE TITLE
Humble "Exclude between same domain" improvement request

### ISSUE THREAD

**Issue by crssi** [tumpio/requestcontrol#119]
Is it possible to extend the `Exclude between same domain` option into possibility of current and `Exclude between same domain and subdomain`.

You can check the library https://github.com/lupomontero/psl which helps to overcome the problems.
There are other extensions using this solution as [Temporary Containers](https://addons.mozilla.org/firefox/addon/temporary-containers/), [Privacy-Oriented Origin Policy](https://addons.mozilla.org/firefox/addon/privacy-oriented-origin-policy/), [Skip Redirect](https://addons.mozilla.org/firefox/addon/skip-redirect/), ...

In the same time, why this option is allowed to be used only for `Filter` action and not for the other actions as well?

Thank you and cheers

**Comment by crssi** [comment]
In case of implementing the requested you can also use it for a TLD wildcard solution and can remove the current needing to enter a list of TLDs. 😉

**Comment by tumpio** [comment]
Request Control uses [tldts](https://github.com/remusao/tldts). Is this option not working as expected?

It is also possible to match requests by origin of request (same domain, third party domain, same origin,..). This option can be found under "Extra URL matchers".

**Comment by crssi** [comment]
Oh... that great.

So when I would use for example `google.*` for host, then I can use `*` in Top-level domain list to make a google domain match for all TLDs?

**Comment by tumpio** [comment]
No, the TLD wild card is not supported currently.

**Comment by crssi** [comment]
This is the only thing that it holds me back from the very beginning. 😢 
Do you have any plans to support it?
If so, do you have any ETA?

Thank you @tumpio and cheers
