### ISSUE TITLE
copy cleaned link

### ISSUE THREAD

**Issue by atomGit** [tumpio/requestcontrol#12]
would be nice to be able to copy the cleaned link (after being processed by RC) to the clipboard

**Comment by tumpio** [comment]
I have planned to add some information to the indicator icon popup on the url bar. Displaying the request details could be added there.

**Comment by tumpio** [comment]
Added in 1.6.1

**Comment by ldgbc** [comment]
Didn't notice that this feature were added. Or maybe I'm reading it wrong. Anyway #1 for reference.
