### ISSUE TITLE
No longer removing DuckDuckGo's tracking parameter

### ISSUE THREAD

**Issue by southwindcg** [tumpio/requestcontrol#121]
The DuckDuckGo search plugin built-in to Firefox adds a query parameter *t* to searches that includes the platform of the computer doing the search. For example, my Linux Mint machine's URL would look like this:

> https://duckduckgo.com/?t=lm&q=test

I have a document filter rule that used to remove this query parameter *t*, but it's no longer working.

**Comment by southwindcg** [comment]
Edit: it seems *no parameters* are being removed at this time. Can anyone else confirm this?

**Comment by EchoDev** [comment]
I'm having issues with removing tracking parameters too, but only in some cases.
Example 

```
Settings:
Pattern
Scheme: http/https
Host: youtube.com youtube.be
Path: *
Types: Document
Action: Filter
List of trimmed query parameters: app attribution_link feature
```

`https://www.youtube.com/watch?v=OipJYWhMi3k&feature=em-uploademail`

Expected URL: `https://www.youtube.com/watch?v=OipJYWhMi3k`
Actual URL: `https://www.youtube.com/watch?v=OipJYWhMi3k&feature=em-uploademail`


I have a few other filters to trim query parameters and those work fine. Not sure what the issues is here. Funny enough when I test this filter from the options menu it returns the expected URL.

**Comment by EchoDev** [comment]
Huh I just think I found out why the filter above isn't working. I have a (default?) filter that filters utm_* and ref_* parameters from any URL. When I disable that filter the youtube filter works again. Is there an issue with multiple filters applied to a single URL?

**Comment by southwindcg** [comment]
I can confirm, I have one of those "any URL" filters and disabling it fixed my broken DuckDuckGo filter too.

**Comment by tumpio** [comment]
Fixed in 1.15.2.

**Comment by EchoDev** [comment]
Can confirm it is fixed

**Comment by FatOrangutan** [comment]
Doesn't seem to have been fixed in its entirety. I am still seeing a case where the `Test selected` button for a given url gives the expected output but Request Control doesn't actually redirect the given url to that output.

Need to test more before I can come up with reproducible steps but FWIW, I have a filter rule matching the `document` and some redirect rules matching `image`'s in the document. The filter rule isn't working while the redirect rules are. Disabling the redirect rule leads to the filter rule working as expected.

**Comment by FatOrangutan** [comment]
STR:

1. Import the following 2 rules[1] into Request Control: 
[buggy rules.txt](https://github.com/tumpio/requestcontrol/files/4429953/buggy.rules.txt)
2. Open this link: https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/?src=search

ER: Request Control redirects to https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/

AR: It doesn't.

<details>
<summary>GIF:</summary>

![bug](https://user-images.githubusercontent.com/8336638/78406146-a440df00-761f-11ea-81f7-bacf5f0dc3d5.gif)
</details>

[1] Rule 1 is:
Pattern: `addons.mozilla.org` `*?*`
URL Parameter: `src`

Rule 2 is:
Pattern: `addons.mozilla.org` `*/addon/*`
Regex: `https://addons.mozilla.org/en-US/{pathname/.+?(?=(firefox|android))/}{search}`

**Comment by geeknik** [comment]
@FatOrangutan I think you have to change some entries under about:config in order for extensions to work on AMO or AMO links.

**Comment by FatOrangutan** [comment]
I should have included in this in my previous message: I do have `extensions.webextensions.restrictedDomains` set to an empty string and the issue I describe is a recent regression - the rules work as expected with Request Control v1.14.0.
