### ISSUE TITLE
Is this compatible with uBlock Origin? If so, what am I doing wrong?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [tumpio/requestcontrol#122]
uBlock Origin has a built-in rule that blocks a URL like this:

    http://www.jdoqocy.com/click-6305441-13212017?URL=
        https%3A%2F%2Fwww.fanatical.com%2Fen%2Fdlc%2Fstellaris-federations

i.e. I'll see a screen like this when clicking it:

<img width="810" alt="Screen Shot 2020-03-18 at 08 01 05" src="https://user-images.githubusercontent.com/200/76963244-bcf68880-68ee-11ea-8f49-6794d67fa809.png">

Now, I've tried to add a Request Control rule to skip that domain:

<img width="796" alt="Screen Shot 2020-03-18 at 08 03 12" src="https://user-images.githubusercontent.com/200/76963374-edd6bd80-68ee-11ea-8841-a16394a045d7.png">

Unfortunately, the additionaly `*.jdoqocy.com` host and capitalized `*URL=*` parameter matching doesn't seem to be working — I still get the same uBlock Origin page when clicking those links.

Do blockers like uBlock Origin run "before" Request Control; i.e. can I not catch a request and redirect it so uBlock Origin isn't bothered? Is there any way around this?

**Comment by ChiefMikeK** [comment]
## `¯\_(ツ)_/¯` Have you tried posting/asking on reddit?  
- [r/uBlockOrigin - The original uBlock project](https://www.reddit.com/r/uBlockOrigin/)
- [r/PrivacyTools IO](https://www.reddit.com/r/privacytoolsIO/)
- First make sure that your RC redirect is working with uBlockOrigin disabled!
### FYI♡ You can also search each of these `r/` forums :100:

**Comment by crssi** [comment]
> Do blockers like uBlock Origin run "before" Request Control; i.e. can I not catch a request and redirect it so uBlock Origin isn't bothered? Is there any way around this?

In your case that is most probably true. The order of execution of webextension depends on the order of initializing webextensions.
Unfortunatelly FF does not provide ordering of webextensions execution, so it is mostly gambling.

You can try to check like this: disable uBO, enable uBO, test the link.... disable RC, enable RC, test the link

Cheers

**Comment by tumpio** [comment]
I personally just click that "Permanently" button which creates a rule (_no-strict-blocking_) for uBlock to allow loading the root document for this domain and let Request control redirect it.

uBlock replaces the tab's document with this "Blocked page" document when strict blocking rule is applied. It is not possible to change this behavior from other extension.
