### ISSUE TITLE
Replace URL?

### ISSUE THREAD

**Issue by chaoscreater** [tumpio/requestcontrol#123]
Hi there,

I've recently come across your app/extension and I'm just wondering if you could assist me in setting this up? I would like to replace the following URL:
https://example.sharepoint.com/*.docx 

With this one:
**ms-word:ofe|u|**https://example.sharepoint.com/*.docx 

And only replace it when there's a .docx in the URL. How can I go about this?

**Comment by ArenaL5** [comment]
I know this is an old question, I hope this is still useful to you (or anyone):

You'd do this:

![replaceURL](https://user-images.githubusercontent.com/37388405/81965672-ab90da80-9618-11ea-9e6c-27707bcb6a7a.png)

```json
  {
    "uuid": "83da1392-768e-4212-8eb1-d33c13934f3d",
    "pattern": {
      "scheme": "*",
      "host": [
        "*"
      ],
      "path": [
        "*.docx"
      ]
    },
    "action": "redirect",
    "active": true,
    "redirectUrl": "**ms-word:ofe|u|**{href}",
    "types": [
      "main_frame"
    ]
  }
```

A redirect-type filter. The use of `{href}` in the screenshot is described in the manual, it means "the whole URL, unchanged". (Yes, you can also edit URLs with this add-on.)

You can open the manual with a button in the top of the screen where you review your rules.
