### ISSUE TITLE
Improve rule editing UX

### ISSUE THREAD

**Issue by geeknik** [tumpio/requestcontrol#128]
Hi and thank you for an excellent extension for Firefox, it is most useful to us. 

### Expected behavior
Don't delete every parameter when I hold down the backspace key.

### Actual behavior
Every parameter is deleted when I hold down the backspace key.

### Steps to reproduce the problem
For whatever reason, when I attempt to edit a rule the text color matches the background color and I can't see what I'm typing into the field. Not really a big deal, however, when I use backspace to remove text from that field, it continues removing EVERYTHING else I had already configured when the backspace key is held down. IMO, for a better user experience, there should be a hard stop for that particular field. 

![request-control](https://user-images.githubusercontent.com/466878/81939964-a56d1080-95bc-11ea-8ba4-1a4179104811.png)

**Comment by ArenaL5** [comment]
Have you tried deleting your half-written parameter with Ctrl+Backspace instead of holding Backspace? It deletes "words" in any modern GUI: it sometimes stops at punctuation, but it should be enough to delete it quickly and safely.

It would still be a good idea to implement it, though.

**Comment by geeknik** [comment]
Hah! I completely forgot about ctrl+backspace. Now to figure out which setting in Firefox messed up the text boxes so I can see what I'm typing.

**Comment by tumpio** [comment]
Changed in 1.15.3 to not use backspace for deleting added entries.
