### ISSUE TITLE
only works per-tab?

### ISSUE THREAD

**Issue by atomGit** [tumpio/requestcontrol#13]
from the description...

> If the matched request URL contains another URL, the request is cancelled and **the tab where the request was made is navigated to the contained URL**.

if i understand this correctly, it seems that if, for example, you middle-click on a Google search result to open the link in a new tab, RC won't clean the redirect - is this correct?

**Comment by tumpio** [comment]
No, RC works on request level. Middle click opens a new tab which makes a new request and RC listens when request is about to be made.

What that means is that for example if the request is made on sub frame level (some ajax call etc, in the background) the tab will navigate to the "cleaned" url. For example this is how google does the redirection tracking when user clicks a search result link (any mouse button).

**Comment by tumpio** [comment]
I will update little how the Filter action works but that will still be what it will do for sub frame requests to actively block Google search tracking. 

You can use the redirection rule instead to apply the "cleaning" on sub frame level without causing any navigation actions.

**Comment by atomGit** [comment]
i'm afraid i'm not knowledgeable enough to completely understand your answer, but my interpretation, combined with the lack of the icon in the address bar when a (google) search result link is opened in a new tab, indicates that RC isn't designed to filter such requests - since i open most search links in a new tab, i need to be able to filter them

i think your extension is probably more powerful than what i actually need

**Comment by tumpio** [comment]
@atomGit sorry for taking long to respond. The pre-defined rule for Google didn't catch main frame requests. I've fixed it. Can you test the latest beta 1.4.3beta4 from
https://addons.mozilla.org/firefox/addon/requestcontrol/versions/1.4.3beta4

> i think your extension is probably more powerful than what i actually need
Well, my goal is to provide easy to use front end for Firefox web request control. You can use it to only do redirection cleaning but there are other use cases for it. Let me know if you have ideas how to improve its usage.

Speaking of link "cleaner" add-ons if they work on document level, and not on request level, they may not stop redirection tracking that is done in background with scripting. How I think most link cleaners work is that they scan a web page for all links and modify their urls. This won't stop llink tracking, if that is what you are looking for.

With RC you can control requests that are send from your browser. It only listens requests that are about to be made, and does not scan any content of web pages nor modify them in any way. This was what I meant with "RC works on request level".

**Comment by atomGit** [comment]
hi again

thanks for explaining how RC works - i have a bit of a better understanding of it now

so it seems that, for example, when you click a google search result, it is normal to see the google redirect URL in the address bar briefly, then the destination URL - as long as the RC icon is in the address bar, the request was still filtered

if i enable RC, the results load as they should, minus the google redirect according to the console (and the icon tool-tip says the request was filtered)

i still prefer the Clean Links method of notifying the user when a link was 'cleaned' - it briefly changes the address bar background color to indicate a cleaned link and this is very noticeable without having to look at the address bar

regarding making RC easier to use, i'm not sure what i can offer outside of redirect cleaning, but in this case, i think it maybe could be simpler - when i enabled the 'redirect' option in the combo control and clicked 'help', this was all over my head - with Clean Links you don't need to have a domain in the rule - you just use RegEx to remove from the target (or request in your case) the junk you don't want to send - for example, the default RegEx that defines what to remove from links is:

`(?:ref|aff)\w*|utm_\w+|(?:merchant|programme|media)ID`

however it is a bit worrying that these link cleaners do not actually prevent script tracking as you point out - in the case of Clean Links, he does have an "event delegation mode", "HTTP observer" and "redirect watcher", however i'm not entirely sure how these work

**Comment by tumpio** [comment]
> i still prefer the Clean Links method of notifying the user when a link was 'cleaned' - it briefly changes the address bar background color to indicate a cleaned link and this is very noticeable without having to look at the address bar

WebExtensions have few ways for creating notifications and they can't modify Firefox user interface. WebExtension can only display an icon in url bar that is linked to the current page, add a new toolbar button or display a desktop notification pop-up.
