### ISSUE TITLE
I was created request control rule for bigl.ua. It's working. Thank you for addons. I think many people needs this rule.

### ISSUE THREAD

**Issue by qwertyuiop2k20** [tumpio/requestcontrol#130]
![Request_Control_Rules--Filter-Bigl ua](https://user-images.githubusercontent.com/62207349/86068834-d5d31600-ba67-11ea-8e7d-3fe5f9380036.png)
![Request_Control_Rules--Filter-Bigl ua--Test](https://user-images.githubusercontent.com/62207349/86068846-dbc8f700-ba67-11ea-9a8a-9fa393b7fb30.png)
![Request_Control_Rules--Filter-Bigl ua--Test2](https://user-images.githubusercontent.com/62207349/86068858-dff51480-ba67-11ea-83f5-92c93dcab140.png)

**Comment by qwertyuiop2k20** [comment]
On this site every product have link with tracking shit.

**Comment by tumpio** [comment]
Thanks for sharing the rule!
