### ISSUE TITLE
New rule creation is broken 

### ISSUE THREAD

**Issue by FatOrangutan** [tumpio/requestcontrol#131]
### Expected behavior
* Created rules work.

### Actual behavior
* The `Host` field is marked as `Please fill out this field` even if it is filled and the rule is considered erroneous. 

### Steps to reproduce the problem
* Be on v1.15.3.
* Try to create any rule.

<details>
<summary>Click for GIF</summary>

![Rule creation errors out](https://user-images.githubusercontent.com/8336638/86482305-5008e080-bd6f-11ea-9756-2a927d8418ed.gif)

</details>

Edit: seems like editing an existing rule is having the same issue.

**Comment by Maryse47** [comment]
I can confirm this. Addon is unusable in current state.

**Comment by FatOrangutan** [comment]
Seems to have been fixed with the recent updates. Closing.
