### ISSUE TITLE
Filter breaks eBay view feedback pages

### ISSUE THREAD

**Issue by welwood08** [tumpio/requestcontrol#14]
`URLSearchParams.toString()` causes `http://feedback.ebay.co.uk/ws/eBayISAPI.dll?ViewFeedback&<other params>` to be transformed into `http://feedback.ebay.co.uk/ws/eBayISAPI.dll?ViewFeedback=&<other params>`, which eBay doesn't understand and redirects to an error page. Potentially other parts of eBay are also broken, but this is the first instance I encountered.

I can't work around this with a redirect rule because redirects are applied before filters, so I'm stuck with whitelisting it (since the filter causing it is for <all_urls>). I'm not sure if there would be any side-effects to either processing redirects after filters or simply `URLSearchParams.toString().replace(/=&/g, '&')`, or if there's a better solution.

**Comment by tumpio** [comment]
Fixed in 
https://addons.mozilla.org/addon/requestcontrol/versions/1.6.1beta1

Can you test that it works? I changed from using URLSearchParams to manual parsing of search params. It seems that URLSearchParams expects always key value pairs.

**Comment by tumpio** [comment]
I can also change the order of redirect and filter rules if that is reasonable even this bug fixed. Currently filter rules process urls after all redirect rules are processed. What do you think which first would be better?

**Comment by welwood08** [comment]
Thanks for the speedy response! I tried to test before looking at the code and found the proposed fix introduced a new problem, see comment attached to 651312c58dea8ce8f8075bfd37ec1e2a959d617d.

As for swapping the order of redirect/filter processing, I'm only just getting started using your addon (hoping to replace CleanLinks), so I don't have many rules already set up that might be affected by such a change. Potentially if other users have used a redirect rule to grab the value of a parameter that is subsequently being filtered then changing the order might break that, but in that case I think the same effect can be obtained with just a redirect.

I was considering filing a feature request even before I hit this bug to allow users to change the ordering of individual rules themselves, both between rules of the same type and between rule types (the latter being what would solve the dilemma of swapping redirect/filter processing, but that's a much bigger task and I don't know if it's worth the effort).

**Comment by tumpio** [comment]
Fixed the params join in:
https://addons.mozilla.org/firefox/addon/requestcontrol/versions/1.6.1beta2

> I was considering filing a feature request even before I hit this bug to allow users to change the ordering of individual rules themselves, both between rules of the same type and between rule types (the latter being what would solve the dilemma of swapping redirect/filter processing, but that's a much bigger task and I don't know if it's worth the effort).

How would you use it? If there are use cases for it I guess it could be implemented.

**Comment by welwood08** [comment]
Confirmed, beta fixes the original issue and the regression.

> How would you use it? If there are use cases for it I guess it could be implemented.
I'd have to mull it over some more as well as see if I encounter any problems that the ability would help work around, if I can come up with a really compelling reason I'll for sure open a new issue.

**Comment by tumpio** [comment]
I tried to think about it and in my opinion the ordering of rules could work if there would be separate rule groups that have their own set of rules to match over some parent request pattern. 

As of now all rules are stored in one list and they don't have any relation to each other which makes the ordering of them vague.

But I don't know if there is need for this.

**Comment by tumpio** [comment]
Fixed in 1.6.1
