### ISSUE TITLE
Changing user-agent

### ISSUE THREAD

**Issue by sergeevabc** [tumpio/requestcontrol#146]
Dear @tumpio,
Is it possible to change user-agent for a specific domain?

**Comment by rusty-snake** [comment]
requestcontrol can rewrite/block the url you visit (in a very powerfull way) but has no rule-type that can edit HTTP-Headers (let alone the JS-UA).
To change you UA anywhere or per domain, I can recommend you [User-Agent Switcher](https://addons.mozilla.org/de/firefox/addon/uaswitcher/).

**Comment by sergeevabc** [comment]
@rusty-snake, thank you for a quick response. Alas, I am looking for an extension that combines headers and redirects tricks.

**Comment by geeknik** [comment]
> Alas, I am looking for an extension that combines headers and redirects tricks.

I like to use [simple modify headers](https://addons.mozilla.org/en-US/firefox/addon/simple-modify-header/) but maybe [header editor](https://addons.mozilla.org/en-US/firefox/addon/header-editor/) or [header mangler](https://addons.mozilla.org/en-US/firefox/addon/http-header-mangler/) is more of what you're looking for? Good luck out there!

**Comment by sergeevabc** [comment]
Tried all of them, settled with [Man in the middle][1] by @dangkyokhoang.

[1]: https://addons.mozilla.org/en-US/firefox/addon/man-in-the-middle/
