### ISSUE TITLE
More information in location-bar icon

### ISSUE THREAD

**Issue by Boolean263** [tumpio/requestcontrol#15]
The Request Control icon appears in the location bar when a request has been filtered.⁺ Clicking on it shows a popup with the same message as the tooltip, "Request was filtered." It'd be neat if the popup had some more detail. Specifically, it'd be neat to see what the original URL was, and the actual URL that was sent.

⁺ So far, filtering is the only action I've experimented with, but I'm sure other actions could show useful content in the popup bubble too.

It would also be cool if clicking in the popup would open a new tab to the Request Control Rules page, ideally with the triggered filter pre-opened. That would be helpful for troubleshooting if a filter isn't working quite right.

**Comment by Boolean263** [comment]
Nosing around the source code a bit, it looks like you're already doing this! I guess that was after 1.6.0 which is the one I currently have installed.

**Comment by tumpio** [comment]
Hi @Boolean263 

1.6.1 includes more details in the popup with a link to the rules page. File a new request if there is something missing from it.

https://github.com/tumpio/requestcontrol/issues/12
