### ISSUE TITLE
Case Sensitive problem

### ISSUE THREAD

**Issue by crssi** [tumpio/requestcontrol#16]
Hi @tumpio 
At least "path" definition is case sensitive, don't know yet for other settings.
This is unpleasant situation. Can you make it case **in**sensitive, please?

Thank you, cheers

**Comment by tumpio** [comment]
URL path is generally case sensitive depending on server configuration. Request Control uses match patterns for request listeners which do not support case insensitivity, see:
https://stackoverflow.com/a/18143014

You can work around this by creating a redirect rule that matches specified host with "*" as path. And then write a redirection rule using case insensitive regular expression rule.

**Comment by Atavic** [comment]
More info [here](https://webmasters.stackexchange.com/questions/69705/should-url-paths-be-case-sensitive).

**Comment by crssi** [comment]
@Atavic What is your opinion? Should matching rules be case sensitive or insensitive?

**Comment by Atavic** [comment]
Case insensitive:
	
- The protocol (http://) - normalize to lower case.
- The host name (example.com) - normalize to lower case. 
- Percent encoded characters (%3F) - normalize to upper case. 

The rest of the URL is generally case sensitive.

**Comment by crssi** [comment]
@tumpio 

> URL path is generally case sensitive depending on server configuration. Request Control uses match patterns for request listeners which do not support case insensitivity, see:
https://stackoverflow.com/a/18143014

Is that for Firefox or Chrome?
I am asking if you can make matching case insensitive in Firefox.

**Comment by tumpio** [comment]
It's for WebExtensions that both Firefox and Chrome uses. Request Control is WebExtension.

Can you give me some examples of your problem (origin and target url), how common is it? Can you use redirect rules for it?

**Comment by tumpio** [comment]
> I am asking if you can make matching case insensitive in Firefox.

I can't change the behaviour of Match Patterns. It could be possible to write a wrapper for it that would work as follow:

- All created rules will use a Match Pattern with "*" as path despite the user's defined paths.
- On request match (which now matches any path) check if any of the user's defined paths match the request path using case insensitive matching.
- Process rule action according to the match result.

Use of this wrapper should be optional configured in settings.

**Comment by crssi** [comment]
[Here](https://github.com/ghacksuserjs/ghacks-user.js/issues/149#issuecomment-310431067) I have two rules... see the 2nd one.
`*signin*` can be `*Signin*` or `*signIn*` or `*SignIn*` or any abreviation... the same goes for other definitions in path.

The same goes for [this](https://github.com/ghacksuserjs/ghacks-user.js/issues/149#issuecomment-310176666) filter.

And [this](https://github.com/ghacksuserjs/ghacks-user.js/issues/149#issuecomment-310175387) one puzzles me too, I am sure It can be done better than my approach.

Any feedback is appreciated.

Just FYI... I will be absent for a 5-7 days and not responding does not mean I am ignoring this thread. ;)

**Comment by tumpio** [comment]
> Here I have two rules... see the 2nd one.
*signin* can be *Signin* or *signIn* or *SignIn* or any abreviation... the same goes for other definitions in path.

I understand the importance now. But as I told above it has to be written as a wrapper to Match Patterns and I have to support both case sensitive and insensitive matching. 

Would some insensitive "flag" work for controlling it? Like "*signin*\i". Or do you have better suggestion?

> The same goes for this and this filter.

Can you write the first one as 

```
Pattern: Any URL
Types: Image
Action: Filter
Filter URL: Off
Trim URL Parameters: Trim all
```
About the second, do you mean that the parameter trimming should be case insensitive too? It can be changed to it by default.

**Comment by crssi** [comment]
> Would some "flag" work for controlling it? Like `\*signin\*\i`. Do you have better suggestion?
Not sure that I understood the way you think of it. Can you be more detailed?

Your suggested filter misses trimming on this sample URL: [https://thechive.files.wordpress.com/2017/06/dd0523324267789bb8beecc5d7914970.jpg?quality=85&strip=info&w=600](https://thechive.files.wordpress.com/2017/06/dd0523324267789bb8beecc5d7914970.jpg?quality=85&strip=info&w=600)
since it should trigger also on `Document` type, but setting it to this type would make a mess on normal URL requests.

Not only the second one. I would like to have everything case insensitive.
And yes, I have understood that API doesn't allow that, which is a shame. I am wonder how gorhill will deal with that for uBO and uMatrix?

What does mean `Embedded document` type? Is that html frame?

What about the last sample I gave you? Do you have any suggestions there? Maybe is better for a new thread?
Maybe this one is also for a new thread: I would like to whitelist every URL where host start with for exaple login... like https://login.*/blahblahblah (* is any domain); https://login.twitter.com/blahblahblah <- not real url, I have made it up for sample

Thank you @tumpio for your time

cheers

**Comment by tumpio** [comment]
Can you list the problems you are having with RC? As far as I have understood you have a global filter rule, and you need to whitelist urls from it based on patterns contained in urls (like *signin* and login.*) and they have to match in case insensitive. Do you have other problems?

> What does mean Embedded document type? Is that html frame?
Embedded document or sub document indicates a document contained within another document (iframes, frames, objects).

**Comment by crssi** [comment]
For this topic only case insensitive is bothering me.
Regex support would be nice generally.

**Comment by tumpio** [comment]
It's bothering me too.. but that doesn't change the fact that I'm not sure how to add support for it. From the use scenarios what you have shared in your previous posts, I can only think of adding a exclude list for rules where you can define patterns of excluded urls where the rule should not apply.

If you have better ideas for it please share. I've documented thoroughly the background.js script that holds all the logic of request listeners and matching. I would appreciate any help. Ideas help too.

**Comment by crssi** [comment]
Will keep in mind and try to sleep over, maybe more than once. If something crosses my mind I will share it for sure.

**Comment by tumpio** [comment]
maybe related #24
