### ISSUE TITLE
Trim params wildcard inconsistency

### ISSUE THREAD

**Issue by welwood08** [tumpio/requestcontrol#17]
This had me confused for quite a while with parameters being trimmed that I didn't intend until I added debug logging manually to see what was going on. Basically when a filter rule's `Trim URL Parameters` value contains more than 1 asterisk, the first asterisk is replaced by the regex pattern `.*` but all the others are left alone.

Personally I'd prefer to just work with regex, but I understand the asterisk replacement is there so users don't have to know regex and to be somewhat consistent with the pattern matching for hosts/paths. It's a bit awkward that it's actually a regex except for the asterisk because it means you can't use an asterisk in any regex context other than `.*` (unless you abuse this bug and know that only the first asterisk works like that).

The obvious fix is to replace `.replace("*", ".*")` with `.replace(/\*/g, ".*")` so all asterisks are replaced, not just the first. A more complete solution might allow the user to deliberately indicate a particular parameter is a regex (eg `/to_be_trim*ed/`) whilst properly treating all others as literal strings, but that seems like a lot of work to get right and performant!

**Comment by tumpio** [comment]
> A more complete solution might allow the user to deliberately indicate a particular parameter is a regex (eg /to_be_trim*ed/) whilst properly treating all others as literal strings, but that seems like a lot of work to get right and performant!

I would like to do it this way. Maybe the regexp pattern of all user defined string literals and regexp patterns can be constructed on rule creation and stored in filter rules. Would it be performant solution?

**Comment by tumpio** [comment]
I changed to it as described in above comment:
https://github.com/tumpio/requestcontrol/commit/f0443a14ebce1fdd8141de9cbed22227674503f2

**Comment by welwood08** [comment]
Nice, I didn't expect to see that so quickly! I spotted a potential logic error that I've commented on. Cool idea to do most of the rule preparation before storing them.

What I was actually alluding to with "seems like a lot of work" regarding literal strings is that the way they are now they're still regex and all other regex features still apply and could trip up unsuspecting users. For example, some sites have parameters that look like `array[item]=value` (certainly PHP treats these as array-like on the server side). If a user tried to add a rule to trim the literal string `array[item]`, the resulting regex is not what they intended to trim. So the "lot of work" is actually in escaping all regex special characters besides asterisk.

In any case, apart from the logic problem I mentioned, it looks like you've resolved my original bug - thanks!

**Comment by tumpio** [comment]
> So the "lot of work" is actually in escaping all regex special characters besides asterisk.
Oh right. I spotted this method for treating user input as literals. It escapes bunch of regex special chars.

> Escaping user input to be treated as a literal string within a regular expression can be accomplished by simple replacement:
> 
> function escapeRegExp(string) {
>   return string.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); // $& means the whole matched string
> }

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

**Comment by welwood08** [comment]
Yep, that looks like the sort of stuff I saw when I hoped to find something simple like `RegExp.escape()`. I assume it's GitHub that's messing with the number of `\` chars in what you pasted, because it changes the meaning completely!

**Comment by tumpio** [comment]
I added regexp escaping and fixed the logic bug 👍 

beta version for testing:
https://addons.mozilla.org/addon/requestcontrol/versions/1.7.0beta2

**Comment by welwood08** [comment]
Found another problem while testing: https://github.com/tumpio/requestcontrol/commit/f0443a14ebce1fdd8141de9cbed22227674503f2#commitcomment-22799171 - caused unintentional trimming of many parameters that matched things like `r` in the middle of a trim rule.

Awesome work adding this feature btw, much more flexible.

**Comment by tumpio** [comment]
Third fix:
https://github.com/tumpio/requestcontrol/commit/7207b62b870c77d53efb5f5e00bd910b1b1e6365

Thanks for testing and doing code review. I need to write some tests.

**Comment by tumpio** [comment]
Fixed in 1.7.0

**Comment by welwood08** [comment]
Confirmed both literal and regexp trim patterns working in 1.7.1beta1.

I encountered a problem with the trim patterns not being migrated during the upgrade from 1.6.0 - see comments on dfef1af25903cf4c028b63fa873b11213b52459c.

**Comment by tumpio** [comment]
Argh.. onInstalled API documentation didn't mention anything that the "previousVersion" property is available starting from version 55 of Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=1313648

I added a fallback for it and I've now disabled 1.7.0 in AMO.

If you didn't do any changes to the rules, you should be able to migrate them installing 1.7.1beta3
