### ISSUE TITLE
Setting pageAction details fails on block rules (1.6.1)

### ISSUE THREAD

**Issue by earthlng** [tumpio/requestcontrol#19]
scheme: `http` host: `*` path: `*` 
`Any type` `Block`

I expected that this filter would block all http requests but it doesn't work.
Any idea why? or how to achieve this? Thanks

**Comment by tumpio** [comment]
Doesn't work at all or for some particular case?

**Comment by earthlng** [comment]
Doesn't work at all.

**Comment by earthlng** [comment]
Is this another webextension limitation you reckon?

**Comment by tumpio** [comment]
No, possibly some bug. Are you using version 1.6.1? can you test if it works in 1.6.0?

**Comment by earthlng** [comment]
Yes I'm using 1.6.1.
1.6.0 blocks the requests :+1:

**Comment by tumpio** [comment]
The url icon (pageAction) was problematic for displaying the applied rule details for block rules. I removed it and added a toolbar button (browserAction) for displaying the details of all applied rules for the current tab.

You can test them in beta version here:
https://addons.mozilla.org/addon/requestcontrol/versions/1.7.0beta2

**Comment by tumpio** [comment]
Fixed in 1.7.0
