### ISSUE TITLE
deviantart filter URL redirection trimming URL parameters

### ISSUE THREAD

**Issue by wfRbeHBASpPKniSGBUvZ** [tumpio/requestcontrol#20]
Trying to open the following link results in &oe=5A0F78B4 being trimmed even though the deviantart rule isn't set to trim anything, breaking the link. I've disabled all other rules to ensure they're not causing the problem.

http://www.deviantart.com/users/outgoing?https://scontent.ftpa1-1.fna.fbcdn.net/v/t1.0-9/19437615_10154946431942669_5896185388243732024_n.jpg?oh=f7eb69d10ee9217944c18955d3a631ad&oe=5A0F78B4

Firefox 54 on Linux Mint 17.1

**Comment by tumpio** [comment]
Fixed in
https://addons.mozilla.org/firefox/addon/requestcontrol/versions/1.7.0beta3

**Comment by tumpio** [comment]
Fixed in 1.7.0
