### ISSUE TITLE
"Cache" problem or?

### ISSUE THREAD

**Issue by crssi** [tumpio/requestcontrol#23]
To reproduce:
Create rules no.1 and no.3 from this issue: [https://github.com/tumpio/requestcontrol/issues/22](https://github.com/tumpio/requestcontrol/issues/22)

Now visit [https://www.kickstarter.com/](https://www.kickstarter.com/), scroll a bit down and you will see images of projects, where rule no.3 is whitelisting the rule no.1. Thats OK.

Now disable rule no.3 and reload the page, where you will see that those images are gone/blocked. Thats OK, since rule no.1 is preventing them to show and whitelisting rule no.3 is disabled.

Now reneable whitelisting rule no.3 and reload the page again and see the result. RC shows that those images are whitelisted, but some are missing and will persist so whatever you do until FF restart.

O god, I hope this make some sense. If not clear what I mean, let me know. English is not my mother language.

**Comment by tumpio** [comment]
hmm this didn't happen to me. It shouldn't be caching problem either.

> O god, I hope this make some sense. If not clear what I mean, let me know. English is not my mother language.

No problem, neither is mine! :)
