### ISSUE TITLE
Filter rule Trim All Except... enhancement suggestion

### ISSUE THREAD

**Issue by crssi** [tumpio/requestcontrol#25]
Could you add under filter rule "Trim All" also exception text box, where all is filtered except the parameters in the, currently not existent, "except" text box?
There are cases when I would like to trim everything except a few parameters.

Cheers

**Comment by tumpio** [comment]
I can add a "negate" button for it.

**Comment by crssi** [comment]
So in this case will remove all except the configured ones?
This would be cool, thanx :)

**Comment by tumpio** [comment]
Beta version to test this:
https://addons.mozilla.org/addon/requestcontrol/versions/1.8.0beta1

**Comment by crssi** [comment]
Cool.
I can see invert trim. It appears to work.
The copy to clipboard doesn't work.
On the rules page all the rules are appearing to be enabled, even those that are not.

Is there any changes about case sensitive?
Do you have any change log? It will be easier to test.

cheers

**Comment by tumpio** [comment]
> The copy to clipboard doesn't work.

Crap 👎 

> On the rules page all the rules are appearing to be enabled, even those that are not.

Fixed 👍 

> Is there any changes about case sensitive?

Yes, but don't expect it any time soon.

> Do you have any change log? It will be easier to test.

I keep changelog for released versions over here https://github.com/tumpio/requestcontrol/blob/master/CHANGELOG

And for beta's there are the commits here:
https://github.com/tumpio/requestcontrol/commits/master

And I try to mark issues using the milestones. E.g. for 1.8.0:
https://github.com/tumpio/requestcontrol/milestone/1
