### ISSUE TITLE
[Feature] [Request] Comment or Description in Rules

### ISSUE THREAD

**Issue by ldgbc** [tumpio/requestcontrol#27]
This might be a obsolete feature or not something that will be added but I will give it a try.

Currently the (my) rules list is quite small so it still easy to remember what each one does and it purpose. But once it get longer (or when I start using other's people rules via import/export that they shared) it will be hard to know what the purpose or this rule.

So can a Comments or more specifically a Description/Naming field be add to accommodate this?

Thank you.

**Comment by tumpio** [comment]
Sounds great. I can make the name and description editable. If not edited they will remain as defaults.

**Comment by tumpio** [comment]
Beta version to test this:
https://addons.mozilla.org/addon/requestcontrol/versions/1.8.0beta1
