### ISSUE TITLE
WebExtensions are inadequate to handle all http requests

### ISSUE THREAD

**Issue by tumpio** [tumpio/requestcontrol#28]
"Some sensitive requests" are unable to be controlled by WebExtensions by API design. These requests are silently ignored without any exception nor warning.

List of bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1380729
https://bugzilla.mozilla.org/show_bug.cgi?id=1380739
https://bugzilla.mozilla.org/show_bug.cgi?id=1334918
https://bugzilla.mozilla.org/show_bug.cgi?id=1330590

Related information:
https://www.ghacks.net/2017/07/13/privacy-blunder-firefox-getaddons-page-google-analytics/

**Comment by tumpio** [comment]
🙃

**Comment by Atavic** [comment]
Setting up a local proxy may be one last resort. I also think that the User Agent string customization will have hard times with webextensions.

**Comment by tumpio** [comment]
There is currently small set of privileged hosts, which are ignored by webRequest API. These maybe controllable in future with an explicit permission. 
> 
>   addons.mozilla.org
>   discovery.addons.mozilla.org
>   testpilot.firefox.com
> 

Further any Firefox "system principal" request ("any request made by Firefox for itself") is out of the scope of webRequest API.
