### ISSUE TITLE
Enhancement: do not redirect if target domain is the same as source

### ISSUE THREAD

**Issue by crssi** [tumpio/requestcontrol#29]
Don't know how to explain this, but will try.

Can you implement exception checkbox under redirect rule, where redirection would not take place if the redirected domain is the same as source... see debate here [https://github.com/sblask/webextension-skip-redirect/issues/30#issue-242171005](https://github.com/sblask/webextension-skip-redirect/issues/30#issue-242171005)

**Comment by tumpio** [comment]
I think this is related to https://github.com/tumpio/requestcontrol/issues/24

**Comment by tumpio** [comment]
I think I can make the url parameters available in exclusion and inclusion patterns, just like in redirection url currently supports the,. But what exactly do you think as a same domain? https://github.com/tumpio/requestcontrol/wiki/Documentation#list-of-named-parameters

**Comment by tumpio** [comment]
The issue you linked is something over complicated than I was thinking about. I'm not sure what you are after with this.

**Comment by crssi** [comment]
Sorry, I was AWOL for last days.
I have choose the wrong wordings I believe. The right would be filtering URL.
I would like to skip URL filtering where domain is the same in the URL and in the parameter.

**Comment by tumpio** [comment]
That may be doable, but not in my top priority. Sorry..

**Comment by crssi** [comment]
I am not trying to make this request top priority. ;)
Thank you

**Comment by tumpio** [comment]
Well, I leave it open and but help wanted tag for it :)

Also do you have more examples to share?

The issue you linked discusses particularly one single use case for "amazon.com" domain. For this particular case URL redirection filtering should not be applied if both the request URL and the filtered redirection URL are both subdomains of the main domain "amazon.com".

https://sellercentral.amazon.com/gp/sc-redirect/seller-page.html/ref=v_sp_storefront%5Bblahblah-mysterious-information%5D&servername=www.amazon.com&type=shops

**Comment by tumpio** [comment]
And how about the multiple top level domains of the same service, like Amazon and Google? Do you require that too?

**Comment by crssi** [comment]
Is that even possible?

**Comment by crssi** [comment]
About examples... I can throw them here when I will stumbled on them, but quite a lot of login pages are cowered out of the box with this solution.

**Comment by tumpio** [comment]
Ok, I leave it open if some one wants to work on it.

**Comment by tumpio** [comment]
1.11.0 has support for this.
