### ISSUE TITLE
Attempting to install the add-on triggers a notification that the extension is corrupt

### ISSUE THREAD

**Issue by MOFTAD** [tumpio/requestcontrol#3]
Firefox version: 51.0.1 (64-bit)
Operating system: Windows 10

The aforementioned notification can be seen [here](http://i.imgur.com/zBXaBvg.png), upon attempting an install through Mozilla's site.

I have attempted on a new profile and the issue persists.

**Comment by tumpio** [comment]
Hello, I drafted a new release with some fixes to the add-on's manifest file that might sort this out. It will be available once Mozilla has reviewed it. Could you confirm that it install correctly?

**Comment by tumpio** [comment]
I'll close this. Report if it happens again.
