### ISSUE TITLE
One guide to explain how to create new rules

### ISSUE THREAD

**Issue by WagnerGMD** [tumpio/requestcontrol#31]
### Expected behavior
```
https://support.mozilla.org/en-US/kb/enable-drm
https://8pecxstudios.com/Forums/index.php
https://support.mozilla.org/en-US/kb/change-your-default-search-settings-firefox
```
### Actual behavior
```
https://support.mozilla.org/en-US/kb/enable-drm?as=u&utm_source=inproduct
https://8pecxstudios.com/Forums/index.php?sid=3fec53ba003fec53ba00
https://support.mozilla.org/en-US/kb/change-your-default-search-settings-firefox?as=u&utm_source=inproduct
```

Hello,

it will easier and lot a better if you can povide an real one example. Then how sould I proceed to remove the UTM and sid (from those links) ?

Kind regards.

**Comment by Atavic** [comment]
By looking at [Testing-links](https://github.com/tumpio/requestcontrol/wiki/Testing-links), I created this rule for your 1st link:

scheme: http/https
host: support.mozilla.org
path: *

Types: Document
Action: filter

Trim URL Parameters: `as` `utm_source`

**Comment by tumpio** [comment]
Hi @WagnerGMD can you give me some details what is currently difficult to understand in rule creation so I can write some examples? Do you want me to illustrate how the pattern works (scheme, host, path), or explain some other things?

**Comment by WagnerGMD** [comment]
Hi,

thank you @Atavic and @tumpio, it seem's to work fine. I was wrong about the path and I can't understand the difference related to **Request Types**.
I was wrong about the **Trim URL Parameters**. it was one word and not two Because on the moment I didn't understand it wasn't split. You might want to add a little note because I was thinking is the touch Enter but in fact, no it's seem to be the comma `,`

**Comment by WagnerGMD** [comment]
Could use the redirection as filters ? Unless there is one erreur in the **Trim URL Parameters**
- `?return_to`
- `return_to`

Then sorry but could explain me what's wrong with GitHub ?
To give one example, instead of this page : 
`https://github.com/login?return_to=%2Fcpriest%2FSnapLinksPlus%2Fissues`
 I just want this one (clean url) : `https://github.com/login`
