### ISSUE TITLE
FR: rules names and comments

### ISSUE THREAD

**Issue by Drugoy** [tumpio/requestcontrol#32]
Feature request:
Please, add the ability to give custom names and custom descriptions to the created rules.

**Comment by tumpio** [comment]
Hi @Drugoy this was requested earlier #27 and added in 1.8.0. It is currently in review queue which has taken ages.. I don't know why AMO reviewers are slow these days. You can try the beta version to test the name and comment editing.

**Comment by Drugoy** [comment]
Thank you.
> I don't know why AMO reviewers are slow these days.

Because mozilla sucks nowadays, it is not what it used to be.
