### ISSUE TITLE
FR: provide a way to reference the text captured by the * in the pattern

### ISSUE THREAD

**Issue by Drugoy** [tumpio/requestcontrol#34]
Feature request:
Please, provide a way to reference the text from the source URL, captured by the * in the pattern.

Say, I want to redirect this URL:
> https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fvid.me%2Fe%2FiVeR9%3Fcard%3D1&amp;url=https%3A%2F%2Fvid.me%2FiVeR9&amp;image=https%3A%2F%2Fd1wst0behutosd.cloudfront.net%2Fvideos%2F16391778%2Fthumb.jpg%3Fv2r1500463663&amp;key=2aa3c4d5f3de4f5b9120b660ad850dc9&amp;type=text%2Fhtml&amp;schema=vid

into this:
> https://vid.me/embedded/iVeR9?autoplay=1

How would I do that?

As you can see, the important string (FiVeR9) is only a PART (not the whole value) of param 'src' (or 'url') from the query of the initial URL.
So I can't reference to the param 'src' as it will return also the part I don't need at all.

If your add-on would save the text that got captured by the * in the pattern and users could reference it - that problem could be solved.

**Comment by tumpio** [comment]
Did you take a look at the [Pattern capturing](https://github.com/tumpio/requestcontrol/blob/master/_locales/en/manual.md#redirect-using-pattern-capturing)?

You can reference patterns of request URL in Redirect rules.

**Comment by Drugoy** [comment]
Yes, I did.
Either I misunderstood some things from it (as the syntax is quite complex and your docs, unfortunately, don't give multiple examples per each passage, which would simplify understanding of the rules for more people), or you misunderstood me now.

As far as I understood the syntax for your add-on - I can only reference a particular parameter using 
```
{parameter}
```
and optionally I can specify a fixed offset for the substring.
But what if the offset is not fixed, but of the various length?
That's what regex capturing groups are for.

**Comment by tumpio** [comment]
Yea, it is not well documented but you can use the regexp capturing groups with the substring replacing. So something like this:

Redirect to: `https://vid.me/embedded/{search/.*src=https%3A%2F%2Fvid.me%2Fe%2F(.*?)%3F.*/$1}?autoplay=1`

Not very pretty.. Is each "*" wildcard possible to be referenced as $1,$2.. in Redirector? Can you show me how you write this rule in Redirector?

**Comment by Drugoy** [comment]
@tumpio thanks for helping me with the rule, but seems like it doesn't fully work.
My rule:
<img src="http://i.imgur.com/3SXW62b.png">
I visit <a href="https://www.reddit.com/r/videos/comments/6reh2m/stretching_day/">this reddit page</a> with an embedded video and hit F12 to open 'Network' tab, where I clear all the logged requests and hit ctrl+shift+r to reload the page with flushing cached items.
And in the log I see this request getting sent to cdn.embedly.com:
<img src="http://i.imgur.com/U2VUbN4.png">
The rule should have prevented from sending data to the cdn.embedly.com, as it matches the request URL and should've been redirected to completely another domain.

Maybe it's the page that's so tricky, because cdn.embedly.com iframe is loaded from another iframe ``src="//www.redditmedia.com/mediaembed/6reh2m"``, but if that's so - I'd call it a bug, because I expect the request redirector add-on to handle all redirects irregardless of how deep they are hidden in sub-document structure.

**Comment by Drugoy** [comment]
p.s.: I've also tried a non-urlencoded rule: ``https://vid.me/embedded/{search/.*src=https://vid.me/e/(.*)\?.*/$1}?autoplay=1`` - the result is the same.

**Comment by tumpio** [comment]
Can't reproduce it with the steps you gave me:

![blaa](https://user-images.githubusercontent.com/6218382/28956639-acacc2ea-78f6-11e7-8688-765aa755d769.png)

**Comment by Drugoy** [comment]
That's odd, it's totally reproducible for me.

Could you, please, make a screenshot of your rule and make sure that in Network tab there's not a single request with 'cdn.embedly.com' in the 'Domain' column?

**Comment by Drugoy** [comment]
@tumpio ping. Could you, please, answer the above question?

**Comment by tumpio** [comment]
Sorry, I'm not able to provide much information here. The rule I tried was identical to yours.

Do you see the rule being triggered by Request Control in the toolbar popup as in my screen shot? 
What are the versions of Firefox and Request Control you are testing with?
Do you experience this behaviour with other rules too?

**Comment by tumpio** [comment]
![kuvakaappaus_2017-08-15_11-44-19](https://user-images.githubusercontent.com/6218382/29308618-28e5259e-81af-11e7-9a77-0cd24064ca16.png)

**Comment by tumpio** [comment]
Do you have other add-ons enabled at the same time that have active redirection rule for the same url?

**Comment by Drugoy** [comment]
I don't know what was that, but the issue now is completely gone.
Thanks for your help!
