### ISSUE TITLE
FR: Provide a way to use RegExp rules instead of wildcard ones

### ISSUE THREAD

**Issue by Drugoy** [tumpio/requestcontrol#35]
Feature request:
Please, add support of regex rules like the Redirector has.

**Comment by tumpio** [comment]
Can you give me some information what this feature request would solve? Where would you specifically need support for regular expression?

In general, matching using regexp is slow. RC currently only supports using plain Match patterns (that is the pattern scheme for the background webRequest API).

**Comment by Drugoy** [comment]
> Can you give me some information what this feature request would solve? Where would you specifically need support for regular expression?

Sometimes I need to reference some sub-string from the value of the parameter and reference to it (re-use it in the 'redirect to' URL).
Your add-on only provides referencing to the whole value of the named parameter and optionally a substring from it using a *fixed length* offset, while I might need an offset of the various length.

I know that regex is slow, so it would be awesome if you *added* it to the currently available type of patterns, not replaced them.

Ideally would be if you would modify the the current GUI in such a way:
1. The user decides whether he wants the input URL pattern to be treated as a single piece, like this:
<img src="https://i.imgur.com/tlpsoWJ.png">
or whether it should be chopped into parts like it is currently done in your add-on:
<img src="https://i.imgur.com/J6WFXRq.png">

2. For each of the input field the user would choose type of pattern to use: regexp or wildcard.

3. Both types of patterns would provide referable capture groups, so that captured strings could be reused in the output URL.

**Comment by Drugoy** [comment]
Now that you've shown in issue 34 how to do that (tricky, but at least it's possible!) - I guess this issue can also be closed.

**Comment by Drugoy** [comment]
p.s.: feel free to re-open issues 34 and 35 if you'd like to improve the UI or something.
