### ISSUE TITLE
Feature request: Block third-party requests

### ISSUE THREAD

**Issue by EchoDev** [tumpio/requestcontrol#36]
Would it be possible to block all third-party requests when on a specific site (Or on any URL)?

Example:
If you go to https://addons.mozilla.org, Firefox makes a request to https://addons.cdn.mozilla.net/ 
With this option it should be possible to block the third party request.

This doesn't seem to be possible with Request Control at the moment. It's only possible to block specific sites but you would have to list them all before you browse the page.

**Comment by tumpio** [comment]
Hi @EchoDev, this requires the base domain comparison which is also requirement for #29.

I opened a request to let extensions to use the Firefox base domain parser.
https://bugzilla.mozilla.org/show_bug.cgi?id=1385835

**Comment by ZenFi** [comment]
Hmmm uMatrix can do all those kind of blocks, wasn't it just ported to FF/webext? Or it might of been uBlock Origin that was, can't remember atm, sry :)

Oh hey since we're talking I saw this same type (request-ext) here on Github done by apparently an East-Asian person (according to code comments) - anyhow that code looked like huh... I'll paste link here when I find it.

**Comment by ZenFi** [comment]
Just posting this as a reference as it's Chrome(ium) and appears to be similar:

https://github.com/evecalm/MyWebrequest/tree/dev

**Comment by tumpio** [comment]
@ZenFi yes many add-ons have their own implementations for it. They relay on the public suffix list which is a "an accurate list of domain name suffixes". This list is used for the same-origin policy which is the standard security measure for cookies in browsers. Firefox has many other use cases for it as well, for example the domain highlighting in the url bar. Legacy add-ons were able to use Firefox own internal APIs and services, but for WebExtensions it is not possible. The request I made was to be able to use the Firefox internal TLD parsing service within (web)extension.

The good news is, it has been accepted already:
https://bugzilla.mozilla.org/show_bug.cgi?id=1315558
