### ISSUE TITLE
For redirected top-level image pages, clicking Save Image still downloads the non-redirected image

### ISSUE THREAD

**Issue by FatOrangutan** [tumpio/requestcontrol#38]
### Expected behavior
*Please see the STR section.*
### Steps to reproduce the problem
* Open the following link: https://pbs.twimg.com/media/C_K3H21W0AAqbIp.jpg. Notice (by hovering over the tab title) that it is a 1200x877px image. Now right click the image > `Save Image As`. Notice that the downloaded image is 1200x877 too, as expected. Leave this tab open.
* Now add the following rule to RequestControl:
![capture](https://user-images.githubusercontent.com/8336638/28833459-0202e964-76fd-11e7-9881-dccb8718a495.PNG)
For easy copy-pasting: `*.twimg.com` `media/*` `{href/(large|small|medium)/orig|/\.(png|jpg|jpeg|gif)$/.$1:orig|/name=[0-9]+x[0-9]+/name=orig}`
* Reload the tab opened in step1. It should get redirected to a URL with `:orig` in the end, which is now a 1606x1174 image. Now right click > `Save Image As`, Notice that the suggested file name to save is the same as step1. Choose a new location or a new name to avoid overwriting. Notice that this downloaded image is still 1200x877, the same size as step1.
* Now while on the same tab as step3, press ctrl+L to select the address bar and press enter. The `:orig` parameter would remain and RequestControl wouldn't have to redirect anything. Right click > `Save Image As`. The suggested file name for saving the image is different from step1 and step3, and the image saved now is 1606x1174, as expected.

Reproducible with RequestControl v1.8.1, on all channels of Firefox, and with other top-level images as well (not just from `twimg.com`).

**Comment by tumpio** [comment]
Hello @FatOrangutan thanks for the detailed bug report! At first look, I think this is a problem with the background API. I need to create a simple test case for it and submit it to the bugzilla.

**Comment by FatOrangutan** [comment]
Gentle bump: @tumpio, were you able to confirm where the bug lies? Thanks.

**Comment by tumpio** [comment]
@FatOrangutan can you add a note if this was resolved or not? I'm sorry for not being able to look on this. I have very little free time to spare on side projects at the moment.

**Comment by FatOrangutan** [comment]
No problem. I filed [Bug 1406253](https://bugzilla.mozilla.org/show_bug.cgi?id=1406253).
