### ISSUE TITLE
URL redirection not working properly with Gmail and Youtube?

### ISSUE THREAD

**Issue by EchoDev** [tumpio/requestcontrol#39]
### Expected behavior
When clicking on a youtube link from Gmail (from an upload notification) the youtube page should load properly
### Actual behavior
When clicking on a youtube link from Gmail (from an upload notification) you end up with a 404 Not Found
### Steps to reproduce the problem
*Go to Gmail
*Click on an upload notification mail and open the video from the link
*You get an 404 Not Found error

This seems to be cause by URLs not being decoded properly? The target url contains text with %3D ( =-sign) and and it seems to be double escaping characters with %253F (?-sign)

Can someone confirm this issue for me. It just might be on my end. Disabling the Google filter solves the issues for me tho.

### Additional info 

https://www.google.com/url?hl=en-GB&q=https://github.com/tumpio/requestcontrol/issues/39%23issuecomment-320343846&source=gmail

Even this link gave issues, it should redirect to the comment from @Atavic 

Expected URL
`https://github.com/tumpio/requestcontrol/issues/39#issuecomment-320343846`
Actual URL
`https://github.com/tumpio/requestcontrol/issues/39%23issuecomment-320343846`

**Comment by Atavic** [comment]
Can you paste the link?

**Comment by EchoDev** [comment]
https://www.google.com/url?hl=en-GB&q=https://github.com/tumpio/requestcontrol/issues/39%23issuecomment-320343846&source=gmail

Even this link gave issues, it should redirect to the comment from @Atavic 

Expected URL
https://github.com/tumpio/requestcontrol/issues/39#issuecomment-320343846
Actual URL
https://github.com/tumpio/requestcontrol/issues/39%23issuecomment-320343846

**Comment by Atavic** [comment]
`#` isn't parsed and stays as `%23`

**Comment by EchoDev** [comment]
@Atavic correct but it seems to happen to pretty much all encoded characters such as `?` and `=`

**Comment by EchoDev** [comment]
Ok I found out why I was getting inconsistent results with testing.

If you left click on an URL in Gmail it will first redirect you to the mail.google.com domain and from there forward you to the requested URL.

If you right click on an URL in Gmail it will straight take you to the URL you want.

When you left click on an URL in Gmail it can give you URLs that don't load correctly.

**Comment by EchoDev** [comment]
Version 1.8.2 seems to fix this issue for me. 

Thanks!

**Comment by tumpio** [comment]
Good to hear! I had time to fix this last week end. @EchoDev thanks for the detailed bug report.
