### ISSUE TITLE
Whitelist mode - filter requests by default

### ISSUE THREAD

**Issue by veaprapre** [tumpio/requestcontrol#4]
Hi! 

Thank you for creating this very interesting addon. I wonder if it's possible to add "whitelist mode", so instead filtering requests for only selected sites it would filter requests for all sites except specified list?

**Comment by tumpio** [comment]
Hello!

That is an interesting idea. That could also be achieved by adding the whitelist support for each rule and then creating a rule with pattern that applies to all sites. That way I wouldn't need to add second "mode" for the add-on.

What do you think? Would that be easy enough to be set up?

**Comment by veaprapre** [comment]
Thank you for the answer. I would like something like this:

- Ability to combine "Filtered out URL parameters" into single line: `utm_source,utm_medium,utm_campaign`

- Ability to combine Hosts into single line: `deviantart.com,google.*,clk.tradedoubler.com`

- Ability to combine Paths into single line: `outgoing?*,url?*,*url=*`

Delimiter could be anything like ","  ";" or space.

Now I would set:

>  Global rule with `host=* path=* rule=Filter Request`

Then I would create two whitelisting rules for my Filter Request:

> Hosts whitelist rule with `host=deviantart.com,google.*,clk.tradedoubler.com`
> Path whitelist rule with `path=outgoing?*,url?*,*url=*`

So my Filter Request won't be effective if matches **one** of those rules.

What do you think? Is it possible?

**Comment by tumpio** [comment]
So each rule would have a list of excluded hosts and paths that will be ignored when the rule matches a request.

It should be rather easy to do. Only have to check if the request url is in the whitelisted domains or paths. I guess creating some sane user interface for it is the hardest part. If you have any ideas for that let me know. :)

**Comment by veaprapre** [comment]
Another possibility would be creating fourth Rule action="Ignore" which will disable all other rules for matching hosts and/or paths.

**Comment by veaprapre** [comment]
Maybe better name for this fourth rule would be "Whitelist". There won't be needed big changes in UI, just one more option in drop down list and rules listed at bottom. I don't know however how it would impact things under the hood.

**Comment by tumpio** [comment]
That is a great idea. 👍 

I just released a new version with better list view of the rules and changed the tracking URL parameters option to one line input. I'll focus on this one next.

**Comment by tumpio** [comment]
Finally had some time to finish this. The new version should be available soon after Mozilla has first reviewed it. I didn't test it much so if you find any issues report them here.
