### ISSUE TITLE
Issue with double question mark rewrited to single question mark, but it should not

### ISSUE THREAD

**Issue by crssi** [tumpio/requestcontrol#40]
### Expected behavior
Do nothing

### Actual behavior
Strips one "?" where there are two "??"

### Steps to reproduce the problem
Create rule:
```js
[
  {
    "pattern": {
      "allUrls": true
    },
    "action": "filter",
    "active": true,
    "skipRedirectionFilter": true,
    "paramsFilter": {
      "values": [
        "xxx"
      ]
    }
  }
]
```

This rule should strip only parameter "xxx".

Visit [https://www.aliexpress.com/item/Xiaomi-Mini-Router-2-4GHz-5GHz-Dual-Band-Max-1167Mbps-Support-Wifi-802-11ac-Xiaomi-Mi/32773978417.html](https://www.aliexpress.com/item/Xiaomi-Mini-Router-2-4GHz-5GHz-Dual-Band-Max-1167Mbps-Support-Wifi-802-11ac-Xiaomi-Mi/32773978417.html)

Every request that has double question mark like "??" is rewrited to single question mark like "?", which is wrong.

**Comment by Atavic** [comment]
On page source there are 4 links with `??` and mor than 30 links with a single `?`

**Comment by crssi** [comment]
Yes. Focus to the 4 links with `??, those `??` get rewritten by this rule to `?` which is wrong, since this rule says that only `xxx` parameter must be stripped and no other modification should be done.

**Comment by tumpio** [comment]
Fixed
https://addons.mozilla.org/addon/requestcontrol/versions/1.8.3pre2
