### ISSUE TITLE
Enhacement: custom rule name for ID and description field

### ISSUE THREAD

**Issue by crssi** [tumpio/requestcontrol#41]
Can rules be enumerated and then under log this number is used to easily identify which rule did the job?

**Comment by crssi** [comment]
^^Or even better... can you add textbox for a nametag and this nametag can be identifier.
Additionally, I am missing custom description textbox (preferable multiline) for documenting/making notes about specific rule.
Cheers

**Comment by tumpio** [comment]
added in 9f1c260
