### ISSUE TITLE
Enhancement: Allow capture groups to be referenced in replacement text of "Substring Replacing"

### ISSUE THREAD

**Issue by m-j-r** [tumpio/requestcontrol#44]
Example - use regex to find a 10 digit number as directory in the pathname, and return only the discovered number
`{pathname/.*\/([0-9]{10})\/.*/\1}`

There are other ways to do this through piping but makes for a mess of a rule.

Thanks!

**Comment by Drugoy** [comment]
#34

**Comment by m-j-r** [comment]
Thanks!
