### ISSUE TITLE
Regex repetition quantifier not supported in pattern captures

### ISSUE THREAD

**Issue by lol2k** [tumpio/requestcontrol#45]
Regex repetition quantifiers ```{n[,n]}``` creates unexpected results.

This doesn't work:
```{pathname/l\.([a-zA-Z]{3,4})$/.$1}```

While this works as expected:
```{pathname/l\.([a-zA-Z][a-zA-Z][a-zA-Z][a-zA-Z]?)$/.$1}```

### Steps to reproduce the problem
* Create new rule with the following properties:

Property | Value
--- | ---
Pattern | ```http/https``` :// ```i.imgur.com``` / ```*l.*```
Types | ```Any type```
Action | ```Redirect```
Redirect to: | ```{origin}{pathname/l\.([a-zA-Z]{3,4})$/.$1}{search}{hash}```

**Example url:**
https://i.imgur.com/cijC2a2l.jpg

### Expected behavior

Redirect to:
https://i.imgur.com/cijC2a2.jpg

### Actual behavior

Redirect (infinite) to:
https://i.imgur.com/cijC2a2l.jpg)$/.$1%7D
https://i.imgur.com/cijC2a2l.jpg)$/.$1%7D)$/.$1%7D
https://i.imgur.com/cijC2a2l.jpg)$/.$1%7D)$/.$1%7D)$/.$1%7D
...
and so on

(the infinite redirects are not part of this issue)

**Comment by tumpio** [comment]
Hello @lol2k 

thanks for the detailed bug report. I'll try to find some free time for fixing it. If you wish to help, you can start working on it.

**Comment by tumpio** [comment]
@lol2k 
Fixed in, let me know how it works:
https://addons.mozilla.org/fi/firefox/addon/requestcontrol/versions/1.8.3pre1
