### ISSUE TITLE
Redirect does not work on addons.mozilla.org

### ISSUE THREAD

**Issue by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [tumpio/requestcontrol#46]
### Expected behavior
The redirect rule redirects from https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/ to https://addons.mozilla.org/ru/firefox/addon/requestcontrol/.

### Actual behavior
The redirect rule does not redirect from https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/ to https://addons.mozilla.org/ru/firefox/addon/requestcontrol/.

### Steps to reproduce the problem
* Install Request Control.
* Set russian locale, russian language.
* Create redirect rule:
** Pattern:
*** scheme: http/https
*** host: addons.mozilla.org
*** path: *
** Types: Document, Sub document, Image, Object, XMLHttpRequest, XML DTD, Font, Media, Imageset, Other
** Action: Redirect
** Redirect To: `{origin}{pathname/^(\/)(?!(?:ru(?:-RU)??|firefox|addon|user)(?=$|[\/?&#]))[^\/?&#]+?((?=$|[\/?&#]).*?)$/$1ru$2}{search}{hash}`
* Open page https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/
The add-on will write that redirected, but does not redirect.

On other domains it works.

**Comment by tumpio** [comment]
Hi there.

this is because of #28. It's because of the limitation set by Mozilla for the WebRequest API.
