### ISSUE TITLE
In rules in regular expressions, the repetition construct {n,m} is not supported

### ISSUE THREAD

**Issue by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [tumpio/requestcontrol#47]
### Expected behavior
The redirect rule redirects from https://example.com/?1234 to https://example.com/.

### Actual behavior
The redirect rule redirects from https://example.com/?1234 to `https://example.com/?1234?(?=$|[?#])|([?&])\d{4,}?[?&])/$1}`, then to `https://example.com/?1234?(?=$|[??(?=$|[?#])|([?&])\d{4,}?[?&])/$1}#])|([?&])\d{4,}?[?&])/$1}`, then to `https://example.com/?1234?(?=$|[??(?=$|[??(?=$|[?#])|([?&])\d{4,}?[?&])/$1}#])|([?&])\d{4,}?[?&])/$1}#])|([?&])\d{4,}?[?&])/$1}`…

### Steps to reproduce the problem
* Install Request Control.
* Create redirect rule:
** Pattern:
*** scheme: http/https
*** host: example.com
*** path: *
** Types: Document
** Action: Redirect
** Redirect To: {origin}{pathname}{search/(?:[?&]\d{4,}?(?=$|[?#])|([?&])\d{4,}?[?&])/$1}{hash}
* Open page https://example.com/?1234
The addon will redirect to the wrong page and will continue to redirect to a stop by the user.
Escaping } does not work. Only rewriting an expression without {n, m} helps, but the expression becomes large and complex.

**Comment by tumpio** [comment]
Is this related to #45 ?

**Comment by Drugoy** [comment]
yes, they are about the same

@tumpio, I don't know about internals of firefox add-ons, but can't you just take some ready made library for regex parsing?

**Comment by tumpio** [comment]
@Drugoy Any JS implementation for it would work. Can you recommend some specific library for it?

**Comment by Drugoy** [comment]
@tumpio actually, I just realized that regex parsing is built-in into JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test

**Comment by Drugoy** [comment]
Turns out JavaScript's regexps don't support lookbehind, so this Node.js lib was born https://github.com/mscdex/node-pcre

**Comment by tumpio** [comment]
@SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU 

Fixed in, please test and let me know how it works
https://addons.mozilla.org/fi/firefox/addon/requestcontrol/versions/1.8.3pre1

**Comment by tumpio** [comment]
Fixed
https://addons.mozilla.org/addon/requestcontrol/versions/1.8.3pre1
