### ISSUE TITLE
Non-standard URLs with multiple question marks are not processed

### ISSUE THREAD

**Issue by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [tumpio/requestcontrol#48]
When deleting parameters from a URL, non-standard URLs (multiple question marks) should also be processed.
### Expected behavior
The filter rule redirects from `http://example.test/path?parameter&utm_source&key=value?utm_medium=abc&parameter&utm_term?key=value&utm_medium=abc#utm_content=utm_campaign?utm_reader=utm_place&utm_reader=utm_place` to `http://example.test/path?parameter&key=value&parameter?key=value#utm_content=utm_campaign?utm_reader=utm_place&utm_reader=utm_place`.
### Actual behavior
The filter rule redirects from `http://example.test/path?parameter&utm_source&key=value?utm_medium=abc&parameter&utm_term?key=value&utm_medium=abc#utm_content=utm_campaign?utm_reader=utm_place&utm_reader=utm_place` to `http://example.test/path?parameter&key=value?utm_medium1=abc&parameter&utm_term1?key=value#utm_content1=utm_campaign1?utm_reader1=utm_place1&utm_reader1=utm_place1`.

### Steps to reproduce the problem
* Install Request Control.
* Create filter rule:
** Pattern: Any URL
** Types: Any type
** Action: Filter
** Filter URL Redirection: Off
** Trim URL Parameters: utm_source, utm_medium, utm_term, utm_content, utm_campaign, utm_reader, utm_place
* Open page `http://example.test/path?parameter&utm_source&key=value?utm_medium=abc&parameter&utm_term?key=value&utm_medium=abc#utm_content=utm_campaign?utm_reader=utm_place&utm_reader=utm_place`

On the Internet, there are pages with links in this way.

**Comment by tumpio** [comment]
Thanks for the detailed bug report. I've not much spare time to put on this, but I'll try to find the time for it. If you can help on it that would be appreciated.

This is related to #40

**Comment by tumpio** [comment]
Fixed 
https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/versions/beta?page=1#version-1.8.3pre2
