### ISSUE TITLE
Protecting Request Control settings by password

### ISSUE THREAD

**Issue by mygithuber** [tumpio/requestcontrol#49]
### Expected behavior
If some sites are blocked by rules, protecting the settings could prevent re-configuring the rules for unwanted outgoing request by curious user.

### Actual behavior
No password is reqired.

**Comment by Drugoy** [comment]
Your suggestion is absolutely ridiculous.
Use the right means and lock your computer/bootloader/os_account/firefox_profile if you need instead.

**Comment by tumpio** [comment]
@mygithuber even if the rules were protected by password, I would still be able to disable or remove the extension. If you are looking for parental controls I can recommend OpenDNS for its simplicity.
