### ISSUE TITLE
Unable to trim URL parameters on youtube?

### ISSUE THREAD

**Issue by EchoDev** [tumpio/requestcontrol#50]
How my trim filter is set up:

Pattern 
scheme http/https 
host *.youtube.com *youtu.be 
path *
Types Document sub document
Action Filter
Filter URL Redirection Off
trim URL parameters attribution_link feature app

### Expected behavior
https://www.youtube.com/watch?v=yWtFGtIlzyQ&feature=em-uploademail should turn into https://www.youtube.com/watch?v=yWtFGtIlzyQ

### Actual behavior
URL stays https://www.youtube.com/watch?v=yWtFGtIlzyQ&feature=em-uploademail
### Steps to reproduce the problem
* Set the filter as shown above
* Go to https://www.youtube.com/watch?v=yWtFGtIlzyQ&feature=em-uploademail
* Link stays the same

I should note that my other filters do work. This is the only one that doesn't seem to want to work.
Using Firefox 58b5

edit:

Hmm..Seems that none of my URL trimming rules work. I have utm_* and ref_* trimming for all URLs but non of them get trimmed.

**Comment by EchoDev** [comment]
I went back to version 1.8.3 and that one did seem to work properly. Seems like something caused trimming URLs not to work in version 1.8.4

**Comment by tumpio** [comment]
Fixed in 1.8.5
