### ISSUE TITLE
[Feature Request] Ability to temporarily disable all redirections from the toolbar button's panel itself

### ISSUE THREAD

**Issue by FatOrangutan** [tumpio/requestcontrol#52]
Would be useful sometimes, especially because rules are often written on a trial and error basis, so you tend to run into url's you hadn't anticipated. [Redirector](https://addons.mozilla.org/en-US/firefox/addon/redirector/) offers something similar.

**Comment by tumpio** [comment]
Do you mean an ability to disable rules (all?) temporarily or an ability to add a rule temporarily?

How would you add this ability to the panel?

**Comment by FatOrangutan** [comment]
An ability to disable all rules temporarily.

>How would you add this ability to the panel?

Just have a button there. Like how Redirector does:
![capture](https://user-images.githubusercontent.com/8336638/34094855-ed80c9b0-e3f4-11e7-8119-1d762a9f2924.PNG)

**Comment by tumpio** [comment]
Looks nice

**Comment by tumpio** [comment]
Added in
https://github.com/tumpio/requestcontrol/commit/e9ae485ebd41d8a1ebee7e8d86963f54693f0238

**Comment by FatOrangutan** [comment]
@tumpio : gentle bump, could you push the update to AMO?
