### ISSUE TITLE
One next features could be about referer ?

### ISSUE THREAD

**Issue by WagnerGMD** [tumpio/requestcontrol#54]
Hello,

I'm just wonder : 
- Did you already think about ? (No I didn't found a topic (or issue, etc) on this matter.
- What's your opinion on the **HTTP referer** ?
- Do you believe it could be one new features ?

If you need one good example, you can take the addon **RefControl** :
- https://addons.mozilla.org/en-US/firefox/addon/refcontrol/
- http://www.stardrifter.org/refcontrol/
- and the page create for test : http://www.stardrifter.org/cgi-bin/ref.cgi

Kind regards.

**PS :** You had closed my previous post. So I couldn't update it neither let you know the good news. Because the trouble was solved (after a few months) by an update (it was probably one bad versions (between **Request Control_v1.8.2** and **Request Control_v1.8.3** or let's say just buggy) to **Request Control_v1.8.6**). But I wasn't aware about them until the last decemder (yes it was by luck).
And just one **little advice : don't forget to keep the people inform.** Because the trouble was cause by the addon **Request Control** itself.
At the end, thank you for these updates.

**Comment by anewuser** [comment]
I've replaced RefControl with this: https://addons.mozilla.org/addon/smart-referer/.

**Comment by WagnerGMD** [comment]
Thank you @anewuser for the suggestion. Because the last times (years) no it wasn't good idea (at the moment, no it didn't work fine). Perhaps it's time to give another try ? I don't know but I will think about.

**Comment by anewuser** [comment]
It works fine for me.
