### ISSUE TITLE
Wildcard for all possible TLDs

### ISSUE THREAD

**Issue by anewuser** [tumpio/requestcontrol#55]
Is there any specific reason why you haven't added support to `*` or `.*` in the `Top-level domains` field to have more generic rules for entities like `google.*` and `blogspot.*`? This rule included by default is the best example of why having to manually insert TLDs can get very troublesome:

![Screenshot](https://user-images.githubusercontent.com/6733770/37127278-d7ea99d0-2253-11e8-8211-5f2fc835760b.png)

**Comment by tumpio** [comment]
That default rule includes all the TLDs of Google Search. Any other TLD would not be Google's. Matching request by all currently known TLDs is possible but I would like to use Firefox own implementation for it. See bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1315558

**Comment by tumpio** [comment]
Probably Include and Exclude patterns in Extra URL Matchers (that were added after this issue) can be used instead of matching to "all TLDs".
