### ISSUE TITLE
Can't add \w{1,2} to "Trim URL parameters"

### ISSUE THREAD

**Issue by anewuser** [tumpio/requestcontrol#58]
### Expected behavior
Adding `/p\w_rd_\w{1,2}/` to trim parameters.

### Actual behavior
It's impossible to do that even by copying and pasting this regex, since commas are always interpreted as limiters.

### Steps to reproduce the problem
* Try to add  `/p\w_rd_\w{1,2}/` to the "Trim URL parameters" field of a filtering rule.

`\w\w?` can be used as a workaround for this specific rule, but this is just an example to describe the problem.

**Comment by tumpio** [comment]
Fixed in 1.9.1
