### ISSUE TITLE
Option to disable status icon (badge changes) about whitelisted entries

### ISSUE THREAD

**Issue by anewuser** [tumpio/requestcontrol#59]
I like that your extension shows the number of applied rules for the current site to help debug problems, but seeing it for whitelisted entries can be distracting. Would it be possible to add an option to disable it for whitelisted entries only?

**Comment by tumpio** [comment]
Would this option also control if the whitelisted entries are shown inside the popup panel or just the badge updates?

**Comment by tumpio** [comment]
> The background of the popup panel turns black when there are many entries (over 12) and I scroll down, by the way. Not sure if this is a Firefox glitch.

Does this still happen on Firefox 60.0.2?

**Comment by anewuser** [comment]
It does:

![screencast](https://user-images.githubusercontent.com/6733770/41822102-f3b7d598-77c0-11e8-80a0-6abf52a90732.gif)

**Comment by anewuser** [comment]
Firefox 61.0 seems to have fixed the color problem.

**Comment by anewuser** [comment]
@tumpio The changelog is empty - https://addons.mozilla.org/addon/requestcontrol/versions/.

**Comment by tumpio** [comment]
@anewuser  added now, thanks for letting me know.
