### ISSUE TITLE
Amazon > Amazon Smile redirect issue

### ISSUE THREAD

**Issue by vertigo220** [tumpio/requestcontrol#61]
I'm trying to set this to automatically redirect me from www.amazon.com to smile.amazon.com to make purchases but am having trouble. My first thought was to use the cart link (https://www.amazon.com/gp/cart/view.html/ref=nav_cart) and replace the www with smile, but it just gave an error if I wasn't already logged in, so that option was out. I then figured I'd just redirect from that link to smile.amazon.com (vs the whole link with www replaced by smile), and that way if I'm not logged in, I get the login page, and if I am I get the main Amazon Smile page, at which point I could just click the cart again.

While that's an acceptable compromise, I was hoping to do better, and so I figured I could do the redirect when accessing the checkout page, which you have to be signed in for the checkout button to even be available, which would solve that issue. So I set up a redirect filter for www.amazon.com/gp/buy/* but it doesn't work when clicking on the checkout button. Once on the checkout page, if I refresh the page it redirects. Likewise, if I enter the whole checkout URL (https://www.amazon.com/gp/buy/spc/handlers/display.html?hasWorkingJavascript=1) manually and go directly to it the redirect works. I suspect the issue is that the checkout button isn't a normal link (hovering over it doesn't provide a link tooltip and right-clicking it doesn't provide any link options) and is probably using javascript. Still, it seems like the redirect should work as soon as the browser receives the address.

It would be nice if this could be made to work. Also, I think this filter should be pre-made in the add-on, as it seems like it would be a fairly commonly desired one, and I probably wouldn't have even thought to do it if not for reading a review where someone else said they did it.

Edit: I tried to do it with the Redirector add-on (https://addons.mozilla.org/en-US/firefox/addon/redirector/) and had the same results. Hopefully this isn't a hard limitation and is something that can be resolved, but the fact both add-ons do the same thing isn't promising.

### Expected behavior

Redirect should occur when clicking the button/link

### Actual behavior

Redirect doesn't occur except by directly entering the address

### Steps to reproduce the problem

See above

**Comment by crssi** [comment]
Did you declare redirection protocol?
Under `Redirect To` use `{protocol}//smile.amazon.com` or `https://smile.amazon.com`.

Cheers

**Comment by vertigo220** [comment]
I did:

https://smile.amazon.com{pathname}

Which brings up another point: should it be necessary to leave out the / after the TLD (.com)? That doesn't seem right, but including it caused it to redirect to smile.amazon.com//...

**Comment by crssi** [comment]
Yes, it should leave out `/`... so like `{protocol}//smile.amazon.com{pathname}`, but do not forget to enter `*` under `pattern` `path` section.

This will make your rule work... but this doesn't mean that amazon application will understand... I think it will not and will break.

**Comment by vertigo220** [comment]
I have the star. I have:

http/https     ://     www.amazon.com     /     gp/buy/*
Document
Redirect
https://smile.amazon.com{pathname}

Like I said, it does work, but only when refreshing the www.amazon link or entering it directly. Clicking the checkout button, which takes you to that link, is what doesn't work. So the rule is correct, I'm just trying to ascertain whether the fact it doesn't work under the specific circumstance of clicking the button to go there is a bug in the add-on, and therefore something that can be fixed, or if it's a limit of redirecting, and not something that can be solved, in which case I'll have to unfortunately go with the less elegant solution of having the cart link take me to smile.amazon.com and then have to click on the cart link again. Unless, of course, someone with more knowledge in this area can provide a better solution.

**Comment by tumpio** [comment]
>  Likewise, if I enter the whole checkout URL (https://www.amazon.com/gp/buy/spc/handlers/display.html?hasWorkingJavascript=1) manually and go directly to it the redirect works. I suspect the issue is that the checkout button isn't a normal link (hovering over it doesn't provide a link tooltip and right-clicking it doesn't provide any link options) and is probably using javascript. Still, it seems like the redirect should work as soon as the browser receives the address.

You check what requests Firefox sends when you click the button using the Firefox Network Monitor. Here is tutorial for using it:
https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor

**Comment by tumpio** [comment]
Nice to hear! I'll close this issue.
