### ISSUE TITLE
Second path not matched

### ISSUE THREAD

**Issue by anewuser** [tumpio/requestcontrol#66]
### Expected behavior
Add another path to the default Google rule.

### Actual behavior
Only the first path is matched.

### Steps to reproduce the problem
* Add `search?*` to the paths of the default Google rule.
* Test it against `https://www.google.com/url` - it is matched
* Test it against `https://www.google.com/search` - no match.

If you invert their order, `search` works, but `url` doesn't.

Request Control 1.9.1
Firefox 60

**Comment by tumpio** [comment]
fixed in 1.9.2
