### ISSUE TITLE
iframe isn't redirected to https

### ISSUE THREAD

**Issue by anewuser** [tumpio/requestcontrol#67]
`iframes` are blocked as mixed active content instead of being redirected to `https`.

Example: https://anewuser.github.io/iframetest/

```
[
  {
    "pattern": {
      "scheme": "http",
      "host": [
        "example.org"
      ],
      "path": [
        "*"
      ]
    },
    "action": "redirect",
    "active": true,
    "redirectUrl": "[protocol=https]"
  }
]
```

Request Control 1.9.2
Firefox 60.0.1 (64-bit)
Windows 10

**Comment by tumpio** [comment]
Because Firefox blocks loading the mixed active content, the request is never made in the first place. Thus Request Control never sees this request being made.

**Comment by anewuser** [comment]
I thought that the extension could be able to manipulate everything before the final request was made. Sorry.

**Comment by tumpio** [comment]
Relates to https://bugzilla.mozilla.org/show_bug.cgi?id=1450965
