### ISSUE TITLE
Icon is confusing

### ISSUE THREAD

**Issue by vertigo220** [tumpio/requestcontrol#70]
I personally find the icon to be a bit confusing, as the disabled one actually looks more "enabled" than then enabled one. I'd like to suggest having a discussion about possibilities for improving it to make it more clear when it's enabled vs disabled.

**Comment by anewuser** [comment]
It looks fine with the dark theme.

**Comment by tumpio** [comment]
I'm open for new icon design. You can find the icons here:
https://github.com/tumpio/requestcontrol/tree/master/icons

**Comment by vertigo220** [comment]
Sorry. I'm using Waterfox 56 with default theme. Here's what it looks like:

![image](https://user-images.githubusercontent.com/12024557/40592376-58e63968-61ec-11e8-86c3-08670f030e5e.png)

**Comment by tumpio** [comment]
Better?

Blue enabled icon:
![kuvakaappaus - 2018-06-21 12-13-11](https://user-images.githubusercontent.com/6218382/41709699-84291794-754c-11e8-8788-4c6a96611413.png)
![kuvakaappaus - 2018-06-21 12-15-10](https://user-images.githubusercontent.com/6218382/41709790-c4d98a3a-754c-11e8-9ed8-e3a80c94936a.png)

Grey disabled icon:
![kuvakaappaus - 2018-06-21 12-13-57](https://user-images.githubusercontent.com/6218382/41709730-9b89c96a-754c-11e8-9aa0-4b704322c9c2.png)
![kuvakaappaus - 2018-06-21 12-14-34](https://user-images.githubusercontent.com/6218382/41709765-ae5ad084-754c-11e8-85e6-6ff2dddb0278.png)
