### ISSUE TITLE
Option to choose the query parameter used for redirects

### ISSUE THREAD

**Issue by rhendric** [tumpio/requestcontrol#72]
When executing a filter rule, in the case when a request URL has multiple query parameters that are valid URLs, RequestControl currently picks the first one as the URL to redirect to. I'd like to have a way to specify that a particular named parameter is the one to use.

For example, the outbound links on `vulture.com` articles ([example](http://www.vulture.com/2018/05/the-end-of-nature-at-storm-king-art-center-in-new-york.html)), when clicked, take you through a `go.redirectingat.com` URL that includes an `sref` parameter which contains the URL of the article you're coming from, as well as a `url` parameter that contains the URL I'd like to be able to redirect to. But since `sref` precedes `url`, a filter redirect would just dump me back to where I came from.

**Comment by rhendric** [comment]
I did try that before submitting this issue to see if it would work, so it's not completely unintuitive. Yet another option would be to allow substituting (percent-decoded, of course) search parameters somehow into redirect rules instead of using a filter rule for this. Something like `{search.url}` (to extract the parameter named `url`), perhaps.

In my opinion, these options rank, from most to least intuitive:
1. Option to specify `url` as the parameter to use for filter redirects
2. Allow search parameters in redirect rule substitutions (`{search.url}` or some other syntax)
3. Trimming unwanted parameters before choosing a filter redirect

The reason I rank your proposal last is because I think it's both more straightforward to say what I want instead of listing the several possibilities that I don't want, and more robust against websites adding new search parameters in the future. But anything is better than nothing!

**Comment by anewuser** [comment]
This very specific case could be solved with a simple regex in case Request Control decoded resulting URLs:

    test: http://go.redirectingat.com/?xs=1&id=xxxxxxx&sref=http%3A%2F%2Fwww.vulture.com%2F2018%2F05%2Fthe-end-of-nature-at-storm-king-art-center-in-new-york.html&xcust=xxxxxxxx&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FNathaniel_Parker_Willis
    regex: {href/.*url=(.*)/$1}
    result: https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FNathaniel_Parker_Willis

**Comment by tumpio** [comment]
@anewuser I like your suggestion.

I'll add couple of string decoding and encoding methods:

```
|decodeURI
|encodeURI
|decodeURIComponent
|encodeURIComponent
|decodeBase64
|encodeBase64
```

**Comment by rhendric** [comment]
It seems a shame to make people write a manual regex parser like `{search/.*[?&]url=([^&]*).*/decodeURIComponent($1)}` instead of `{search.url}`. The `URL` class already parses search parameters into a Map called `searchParams`; it would be easy for you to parse `{search.whatever}` into a redirect pattern that resolves `requestURL.searchParams.get('whatever')`. Why ask users to do that work with regexes?

**Comment by rhendric** [comment]
Can confirm working! I do appreciate the work put into this solution, even if I still think it's not the cleanest way. I may still try my luck with a PR for my idea when I have a little more free time.

**Comment by anewuser** [comment]
Ah, I didn't know that you had added it too. 

    [href={search.url}]
