### ISSUE TITLE
Ending character of character set `]` is seen as end of redirect instruction.

### ISSUE THREAD

**Issue by gwarser** [tumpio/requestcontrol#73]
### Expected behavior
Redirect
- https://en.m.wikipedia.org/wiki/Main_Page
to
- https://en.wikipedia.org/wiki/Main_Page
by
`[hostname={hostname/\.[mi]\./.}]`

### Actual behavior
No redirection.
`> Invalid target URL: \./.}]`
`[hostname={hostname/\.(m|i)\./.}]` works fine.

***

Similar to https://github.com/tumpio/requestcontrol/issues/69 I cannot find real use case for now. I choose `[mi]` because I have seen mobile websites with `i` subdomain (for iPhone?)

**Comment by tumpio** [comment]
Fixed in https://github.com/tumpio/requestcontrol/commit/8da52b0a009676dd66aa2a82c7a4f203c677c41f

Thanks for reporting!

**Comment by anewuser** [comment]
@gwarser  Just out of curiosity, why do you need that `i`?

`https://en.i.wikipedia.org/wiki/test` gives an error.

**Comment by gwarser** [comment]
I wanted to make this redirection more universal. My first idea was something like this
`[hostname={hostname/([.^])m\./$1}]` dot or "start of string".
Should give:
`en.m.example.com` -> `en.example.com`
`m.example.com` -> `example.com`
I did not know that `^` is literal in character sets and found this parsing bug when debugging.

`i` is used for repro steps because _some_ pages use(d) it for mobile versions, for example https://i.wykop.pl/
