### ISSUE TITLE
[Feature request] Action "Open in private browsing" and also "Open in new private browsing window"

### ISSUE THREAD

**Issue by daalja** [tumpio/requestcontrol#74]
How about adding an action "Open in private browsing" and also "Open in new private browsing window"? It's a regular use case I have, opening specific sites like $m$zon in new private windows, because I don't like to see what I was interested in lately nor should their bots analyze every lookup I do.

**Comment by tumpio** [comment]
Hi @daalja, I like your feature request. Firefox also applies its tracking protection feature automatically for private browsing windows.

Can you describe more what would be the difference between these two separate actions? Would one action "Open in private browsing" be enough?

**Comment by daalja** [comment]
Hi @tumpio. Firefox has the option to open a new private window being already in private mode. Thinking about it I guess it would be a rarely chosen way to open every request in a new private window.
But if somebody really would like this feature in the future it might only need a separate checkbox "Open in a new window" then.
Thx a lot.

**Comment by anewuser** [comment]
You should use [Temporary Containers](https://addons.mozilla.org/addon/temporary-containers/) for that.

**Comment by tumpio** [comment]
For reference on containers:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextualIdentities

**Comment by daalja** [comment]
Thx a lot. I wasn't aware of that. Seems to make this request obsolete.
