### ISSUE TITLE
Version 1.11.0 broken on Waterfox

### ISSUE THREAD

**Issue by MSGithubExodus** [tumpio/requestcontrol#79]
### Expected behavior
Icon menu contains something (Request Control Rules|Disable), extension options page shows something
### Actual behavior
They are empty
### Steps to reproduce the problem
* Install Request Control 1.11.0 from AMO or update from 1.10.1 to 1.11.0
* Click on the icon or go to the browser addon manager and click on the option button of Request Control

This is on Waterfox 56.2.2, Windows 7 64bit. I tested that the problem is here with a new profile too.
Previous Request Control version 1.10.1 had no problem.
On Firefox 61.0.2 I have no problem with version 1.10.1 or 1.11.0 .

**Comment by tumpio** [comment]
Hi @MSGithubExodus , thanks for reporting.

Request Control 1.11.0 requires at minimum Firefox version 60. I forgot to specify this. You can keep using older versions with Waterfox if they work in it. Request Control is a Firefox extension. I have no resources (time) to test and develop it for other browsers at the moment.

**Comment by MSGithubExodus** [comment]
Ok thanks for replying and updating the version requirements on AMO ! I'll keep using 1.10.1 then.

**Comment by anewuser** [comment]
No changelog again - https://addons.mozilla.org/addon/requestcontrol/versions/
