### ISSUE TITLE
Rules import and export

### ISSUE THREAD

**Issue by tumpio** [tumpio/requestcontrol#8]
From user review by U64, March 24, 2017

> My suggestions would be being able to export/import rules and settings (maybe even sync across devices, a la uBlock Origin; but regular export/import to a file works just dandy).

notes

webextension sync support is not yet available on android:
https://bugzilla.mozilla.org/show_bug.cgi?id=1316442

**Comment by tumpio** [comment]
Download API for exporting and file input for importing:
http://stackoverflow.com/a/38838572

**Comment by crssi** [comment]
Hi @tumpio, do you have any ETA for this implemntation?

Anyway... very very good job and thank you for sharing this extension.

**Comment by tumpio** [comment]
Hi @crssi I can't give any ETA other than :soon: I'm working on it :)

If you want to cheer me up buy me a cup of coffee!

**Comment by tumpio** [comment]
@crssi  also which one do you anticipate most, rules import/export or the sync support?

**Comment by crssi** [comment]
Import/Export I would anticipate most. :)
Sync is nice too, but not as important as Import/Export

Thank you

**Comment by crssi** [comment]
Hmm... coffee machine over paypal obviosly broken at Mozilla AMO. :(
I have dropped the profile, with brand new (to avoid confusion with some Extensions and custom preferences), but with no luck.
Will try again later/another day.

**Comment by crssi** [comment]
@tumpio Promised coffee on the way. But crap, had to use Internet Explorer. Even fresh installation of FF v53 and FF v54 did not work,.

**Comment by crssi** [comment]
Been thinking
Maybe you can make export as a download config file generated on the request?
Or the way gorhill implemented this for uBlock Origin and uMatrix.

It would be some real enhancement if there would be an option to export/import single filter... maybe a text box with filter config data in some sort of XML or JSON format.

**Comment by mrdokenny** [comment]
I found a workaround to transfer extension data that should work for all WebExtensions.

Ex. For Request Control which has an ID of `{1b1e6108-2d88-4f0f-a338-01f9dbcccd6f}`

1. Go into your profile and then `browser-extension-data/{1b1e6108-2d88-4f0f-a338-01f9dbcccd6f}`
2. Copy the `storage.js` file
3. Transfer that file into another profile
4. 😉 

But, it'll probably be better to have export/import in the extension itself.

Here's some sample code of how [I did it](https://github.com/mrdokenny/Cookie-AutoDelete/blob/master/extension/settings/settings.js#L209)

**Comment by tumpio** [comment]
@mrdokenny @crssi 

can you try new version with export and import:
https://addons.mozilla.org/addon/requestcontrol/versions/1.7.0beta1

@mrdokenny nice to now about this :)

**Comment by mrdokenny** [comment]
```
function exportObject(name, object) {
    let mimeType = "application/json",
        data = JSON.stringify(object, null, 2),
        blob = new Blob([data], {type: mimeType});
    return browser.downloads.download({
        url: URL.createObjectURL(blob),
        filename: name,
        conflictAction: "overwrite",
        saveAs: true
    }).then(revokeObjectUrl);
}
```
I didn't use the download API because I didn't want to request another permission just for that, but it nice to know that it doesn't have this [one problem](https://bugzilla.mozilla.org/show_bug.cgi?id=1331176), which just uses regular JS.

As for the beta version, importing the rules seem to not take into account duplicates.

 STR:
1. Export rules
2. Import them again
3. See duplicates for the default rules

Another thing is the file upload button can be [stylized](http://geniuscarrier.com/how-to-style-a-html-file-upload-button-in-pure-css/)

**Comment by tumpio** [comment]
Using a downloads API for creating a download seemed quite applicable for the job! :)

Duplicates handling is quite excessive, I think.

> Another thing is the file upload button can be stylized

I'm using bootstrap which doesn't include styling for it.

**Comment by mrdokenny** [comment]
> Duplicates handling is quite excessive, I think.

It depends on how you consider one rule to be the same from another one. 
Ex. You could make it so if the path, types, action are the same, append the hosts into one rule.

> I'm using bootstrap which doesn't include styling for it.

You can overlay the input in a label and use the bootstrap button css on it.
Sample code:
```
<label class="file-upload">
	<input id="importURLS" type="file"/>
	<div id="importURLSText">Upload File</div>
</label>
```

```
.file-upload {
  display: inline-block;
  height: 38px;
  padding: 0 30px;
  color: #555;
  text-align: center;
  font-size: 11px;
  font-weight: 600;
  line-height: 38px;
  letter-spacing: .1rem;
  text-transform: uppercase;
  text-decoration: none;
  white-space: nowrap;
  background-color: transparent;
  border-radius: 4px;
  border: 1px solid #bbb;
  cursor: pointer;
  box-sizing: border-box;	
}

input[type="file"] {
  display: none;
}
```

![capture](https://user-images.githubusercontent.com/17077613/27549895-70ae8d54-5a52-11e7-9ecc-5ea654cbe302.PNG)

**Comment by tumpio** [comment]
I'll leave it here myself. If you want to work on it feel free. I'll consider adding sync support once the android options issue is fixed.

**Comment by ldgbc** [comment]
Cool. There is export and import system now. Anyone want to share some of their rules?
I attached two of mine that I currently use (didn't add many since it wasn't working before with e10s). And it difficult to tell when it does get activated (hidden in the Navigation bar, whereas something like Cleanlinks highlight clean link. Anyway thank you @tumpio tumpio.


[request-control-rules-sharing.zip](https://github.com/tumpio/requestcontrol/files/1132995/request-control-rules-sharing.zip)

**Comment by Atavic** [comment]
@ldgbc nice sharing idea, but what do your rules do?

**Comment by tumpio** [comment]
By the way the wiki is public if you want to create some page for sharing rules there. And if you wish to include some of your rules as default rules in RC, open a new issue for that.

**Comment by tumpio** [comment]
webextension sync support is not yet available on android:
https://bugzilla.mozilla.org/show_bug.cgi?id=1316442

**Comment by crssi** [comment]
It would also be nice to be able to export single rule only. This way it would be easier to share rules between users. ;)

**Comment by tumpio** [comment]
@crssi you can do that by selecting a single rule in the rules view.

**Comment by crssi** [comment]
Haven't seen that... it awesome, ;)

**Comment by tumpio** [comment]
I'm afraid sync support has to wait. Android support is lacking for it.
