### ISSUE TITLE
no rules shows up

### ISSUE THREAD

**Issue by stardusk9** [tumpio/requestcontrol#82]
### Expected behavior
* all rules shows up 
* can export
* rules working
* edit rule link to rule edit page

### Actual behavior
* no rules shows up 
* can't export
* rules working
* edit rule link to blank new tab (link ok, but no edit page shows up)
* clicking export button - TypeError: myOptionsManager.options is undefined

### Steps to reproduce the problem
* mozilla firefox 56.0
* request control 1.10.1
* adding some rules
* installing checkcompatibility2
* changing checkcompat value in about:config
* changing etc... value in about:config
* req. control auto updating (?)
* problem persist after reinstalling addon

**Comment by anewuser** [comment]
Why are you using an ancient version of Firefox?

**Comment by stardusk9** [comment]
since its the last version that support legacy addons.
and ............ 56 released in 2017

**Comment by anewuser** [comment]
Well, you can't expect modern extensions to work on such old versions. Firefox is at version 63 now, and the extended support is at ESR 60.

**Comment by tumpio** [comment]
Version 1.**10**.1 should work with Firefox 56.

**Comment by stardusk9** [comment]
idk whats wrong but nevermind. i have reinstalled firefox.
