### ISSUE TITLE
how to add multiple tags?

### ISSUE THREAD

**Issue by practik** [tumpio/requestcontrol#83]
Hi @tumpio, thank you for creating and maintaining this extension!  I've been using it for a little while now and I have some questions for you.  The first one is:

Is it possible to add more than one tag to a rule? I've been trying to do it and I can't make it work.

If it's not possible, then I'd suggest you give Request Control's "tags" a different name – maybe "labels" – to avoid confusing users. I think the ability to have multiple tags is a pretty fundamental part of the metadata tag concept.

**Comment by tumpio** [comment]
Hi @practik It's not possible to add multiple tags. Would there be use for this?

At least some debug tools use "tag" as the name for the string/label you pass to create a new log entry.

**Comment by practik** [comment]
Thank you, @tumpio. No, I guess it wouldn't be useful to have multiple tags in RC.  I originally thought that the tags in RC were meant to work like metadata tags, but I see now that they have a different function. And if "tag" is a familiar name for that function for most of RC's users, then I guess the name is fine too. I'll close this now.
