### ISSUE TITLE
why is "utm" not an Include for the sample UTM filter?

### ISSUE THREAD

**Issue by practik** [tumpio/requestcontrol#84]
Next question: In your sample filter that removes UTM query parameters from all requests, why is `utm` not listed under Includes? Without it, Request Control applies the rule to every single document request (correct?). Why not apply it only when the request URL includes `utm`?

(By the way, thank you for the sample filters, they've been very helpful)

**Comment by anewuser** [comment]
Please read the manual.

**Comment by practik** [comment]
I did read the manual, and I have already written some rules that use Includes and Excludes in the way you're describing, but surely that's not the only way to use them – ?

One reason to add `utm` as an Include for this rule might be for troubleshooting. Yesterday I wrote a rule that put a webpage into an endless redirect loop. I could see the counter on the RC toolbar icon going up, so I clicked it to see what was happening, and the popover showed that two rules were active: mine and `filter-utm`. That was not helpful for diagnosing the issue.

**Comment by anewuser** [comment]
You're free to use it for whatever you're able to, but there's just no point in always repeating parameters in the "Includes" fields. In order to remove parameters, the extension already obviously checks if they are present in a URL beforehand.

**Comment by practik** [comment]
> there's just no point in always repeating parameters in the "Includes" field

I'm not suggesting that; I'm just asking why it wasn't done in this particular case. And I think @tumpio is the only person who can actually answer that question (assuming they're the creator of that sample filter). I have two guesses about this:

1. Maybe adding `utm` as an Include is less efficient. If so, how much less?
2. Maybe adding `utm` as an Include causes RC to miss some requests that it should be filtering. Logically I can't see how this would be the case, but I'm sure I'm not aware of the all the factors involved.

That second point is the more important one for me. If 1) is true, I'll most likely keep `utm` as an Include for the reason mentioned in my last comment. But if 2) is true, I'll go back to having no Includes on this filter.

**Comment by anewuser** [comment]
I'm sorry but it's pointless for you to write essays without actually showing people your broken rules, so we can fix them for you.

**Comment by anewuser** [comment]
When you seek help or try to point out a problem with a piece of software, you need to provide the exact steps and code that caused the issue, so that we can show you what you did wrong, or confirm that there is indeed a problem with the software. In other words, I'm asking you to export your rules and drag and drop the file to Github.

**Comment by practik** [comment]
> When you seek help or try to point out a problem with a piece of software

I'm not doing either of those things. I'm asking a question about why the `utm-filter` rule was written the way it was, so I can make a more informed decision about how to use it. I'm pretty sure at this point that @tumpio is the only person who can give me a useful answer to that question.

**Comment by anewuser** [comment]
It was written that because it just works. You're just having problems with it because of your own custom rules.

**Comment by practik** [comment]
@anewuser, I'm not having problems with the rule, as I've told you already. Please stop spamming this thread and let @tumpio respond to my question.

**Comment by anewuser** [comment]
Your original question was: " In your sample filter that removes UTM query parameters from all requests, why is utm not listed under Includes?". I gave you the obvious answer. It isn't included because parameters are obviously checked to be present before the extension attempts to remove anything.

Please follow the code of conduct of Github and don't accuse people of "spamming". You're being aggressive because you fail to realize that there's no problem with the extension, despite my attempts to explain it to you.

**Comment by Atavic** [comment]
I strip any Google Analytics UTM Parameter, but there are sites that won't let you login if they are missing.

**Comment by crssi** [comment]
^^ Didn't know that. Do you have any sample site not working due to stripping UTM parameters?
ATM I am stripping `utm_*` and havent noticed any breakages, but would like to optimize it, which is hard to do without sample. ;)

Cheers

**Comment by Atavic** [comment]
Maybe it's soundcloud. I can use it only with ung00gled chromium.

**Comment by Atavic** [comment]
Or Mixcloud, same as above, must use Chromium.

**Comment by crssi** [comment]
I have created accounts at soundcloud and mixcloud.
Using Firefox with user.js and profile described at `https://github.com/crssi/Firefox/blob/master/user-overrides.js` which is supplement to https://github.com/ghacksuserjs/ghacks-user.js.
I am stripping out url parameters `utm_*` and I have no breakages at those two services, login pass, music play pass.
Did I miss something?

Cheers

**Comment by Atavic** [comment]
I also spoof the user agent, that could be my problem.

**Comment by practik** [comment]
Thank you, @tumpio!

In the case of this special rule I can't add `*utm_*` as a path pattern because the match pattern is `all urls`. So I added it as an include instead. I guess I could change the match pattern to `*://*/*utm_*` instead – but would there be any advantage to doing it that way?

**Comment by Atavic** [comment]
```*://*/*utm_*``` and ```*utm_*``` give the same results actually.

For an example, go [here](https://www.mozilla.org/en-US/firefox/) and right click on *Projects*, you'll see ```https://iot.mozilla.org/?utm_source=www.mozilla.org&utm_medium=referral&utm_campaign=nav&utm_content=projects```

**Comment by practik** [comment]
Thanks, @Atavic.

> `*://*/*utm_*` and `*utm_*` give the same results

That's what I thought. I just wondered why @tumpio suggested adding `*utm_*` as a path, which would require changing the current match pattern from `all urls`, instead of an include, which is a simpler solution. But maybe there is no reason. I'm going to assume I'm overthinking all this stuff and close this issue :-)

**Comment by Atavic** [comment]
^ I don't know, maybe because his choice is simply shorter?
