### ISSUE TITLE
why do intermediate URLs appear in browser history?

### ISSUE THREAD

**Issue by practik** [tumpio/requestcontrol#85]
Last question: I've noticed that when a filter or redirect rule is applied, the intermediate URL still appears in the browser history. For example:

If I open
    `https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/`
and click on the "Support Site" link, the URL in the address bar immediately changes to
    `https://github.com/tumpio/requestcontrol/issues`.

But if I check Firefox history, the sequence is:
* `https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/`
* `https://outgoing.prod.mozaws.net/v1/c5606e2dd8ec4b70b6a85da838807814e93024cd75ecd8cbc00f42f41832387c/https%3A//github.com/tumpio/requestcontrol/issues`
* `https://github.com/tumpio/requestcontrol/issues`

Is this correct behavior?

**Comment by anewuser** [comment]
Yes, all manipulated URLs are added to your history even though they aren't being downloaded. The developer would need to make the extension more complex to remove those history entries. You can use this instead and remove all unwanted history entries automatically:

https://addons.mozilla.org/addon/historia/

**Comment by practik** [comment]
Thanks, @anewuser. I thought that would be the answer, but I just wanted to check – when I first saw those history entries I thought maybe Request Control wasn't actually filtering the requests. Historia looks interesting, thanks for the tip!
