### ISSUE TITLE
[Feature request] Respond with local file

### ISSUE THREAD

**Issue by whiver** [tumpio/requestcontrol#87]
Would be great if the Redirect action type could respond a local file to mock a service. Is there a way to do that currently?

**Comment by tumpio** [comment]
Seems to be not currently supported by Firefox:

> Redirections to non-HTTP schemes such as data: are allowed, but they are not currently supported (bug 707624). 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/BlockingResponse

Could you serve the files on localhost with some simple web service?

**Comment by tumpio** [comment]
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server#Running_a_simple_local_HTTP_server

**Comment by whiver** [comment]
Pretty sad. Thanks for the answer, I'll explore this workaround!
