### ISSUE TITLE
Doesn't work on Firefox for Android

### ISSUE THREAD

**Issue by krathalan** [tumpio/requestcontrol#88]
### Expected behavior
I would expect it would work like desktop, where parameters I have specified to get filtered out, get filtered out.

### Actual behavior
Parameters I have specified to get filtered out do not get filtered out.

### Steps to reproduce the problem
* Install Request Control on Firefox for Android or Fennec 
* Filter certain parameters from some sites or all sites
* Navigate to a URL with said parameters
* Notice parameters do not get filtered

Will edit to add imgur link with screenshots after I can see the issue #.
Edit: https://imgur.com/a/HEKwFMh

**Comment by tumpio** [comment]
Next release will support Firefox for Android.

**Comment by anewuser** [comment]
@tumpio I appreciate your work on this extension, but it's a shame that the new design occupies so much space that I have to scroll down to see all the options related to a single rule on a 1920x1080 resolution. Can't you use different styles for desktop and mobile devices?

If you keep the new design, please consider at least highlighting the rules that are selected.

**Comment by tumpio** [comment]
@anewuser 1.12.1 has more compact layout on desktop. If there is something that can be improved, let me know.

**Comment by anewuser** [comment]
Thanks. It's more usable on the desktop now.
