### ISSUE TITLE
Filtering vs Redirect

### ISSUE THREAD

**Issue by AeliusSaionji** [tumpio/requestcontrol#89]
It's not clear to me when a filter is appropriate and when a redirect is necessary. Is the below confusion because I need to use a redirect instead of a filter? Why?

***

I have a url `https://kotaku.com/hd-doom-is-looking-very-nice-1830996796/amp?__twitter_impression=true`

I want to not visit the amp page- it seems to me that this should be easily accomplished by filtering out `amp`. Except, no filter rule I create will filter out `amp` and I do not understand why.

Same for `?__twitter_impression=true`. I tried to create a rule to filter that, but it will not go away. What am I doing wrong?
![image](https://user-images.githubusercontent.com/4342746/50058758-0a63d300-014b-11e9-82b3-0f6ae9c543ab.png)

***

Along the same train of thought- link #10 in this list https://github.com/tumpio/requestcontrol/wiki/Testing-links

It claims "no redirection, only paramers", but I cannot get this to work unless I configure it as a redirect. I am confused. Please help!

**Comment by crssi** [comment]
Its not a parameter filtering.

Try this...
Host: `*`
Path: `*/amp?__*`
Types: `Document`
Action: `Redirect`
Redirect To: `{href/(.*?)amp\?__.*/$1}`

Cheers

**Comment by anewuser** [comment]
In this case, `/amp` isn't a parameter. It's part of the base URL. Filtering is for URL parameters, which come after a question mark. For example:

example.com/lalala/?**utm** =1312
example.com/lalala/amp?**hey**=this&**hi**=that&**_twitter_impression**=foo


Also, to filter `twitter_impression` and similar parameters from all URLs, download this, change the extension to `.json` and import it to the extension:


[twitter_impression.txt](https://github.com/tumpio/requestcontrol/files/2688296/twitter_impression.txt)


This is my full parameters cleaning rule (I've just added the Twitter thing):

[paremeters_cleaning.txt](https://github.com/tumpio/requestcontrol/files/2688301/paremeters_cleaning.txt)

**Comment by AeliusSaionji** [comment]
Thanks!
