### ISSUE TITLE
Order rules alphabetically

### ISSUE THREAD

**Issue by anewuser** [tumpio/requestcontrol#90]
@tumpio what do you think of ordering all rules alphabetically, according to their names?

**Comment by practik** [comment]
I just came on here today to ask for this myself (my rule list is getting rather long). @tumpio, you might also give users the option of ordering the rules alphabetically by tag name.

**Comment by tumpio** [comment]
@anewuser by default? I think the rule list is now ordered by order of creation and rules may change position if modified or action changed. Some ordering functionality could be added.

**Comment by anewuser** [comment]
That would be cool at least optionally. I have over 30 rules.

**Comment by tumpio** [comment]
Added in 1.12.2
