### ISSUE TITLE
Sudden UI Change

### ISSUE THREAD

**Issue by krathalan** [tumpio/requestcontrol#93]
### Expected behavior
I expected the UI to not change without an update. I checked, and the last update was on August 7, 2017, so there's no way that an update could have changed it.

### Actual behavior
The UI is styled differently, and Request Control refuses to accept or parse exceptions to rules. For example, on a lot of my rules, I have exceptions to _not_ filter when the current URL contains "signin", "sign-in", etc. so as to not disturb sign in redirects. I also have exceptions that prevent sites from breaking in other ways. 

Despite having exceptions in my imported rules file, Request Control doesn't seem to load them, display them, allow me to edit them, or recognize them. Because of this, several websites now break for me with Request Control enabled.

### Steps to reproduce the problem
* I'm not sure what caused this issue. I just installed Request Control like I always do.

Here's a screenshot showing the strange UI with no exceptions box:

![screenshot from 2019-01-24 14-05-30](https://user-images.githubusercontent.com/25400030/51711990-4f004b00-1fe2-11e9-86e7-7251f3139669.png)

Edit: uninstalling and reinstalling the addon has no effect. I also experience this issue on a completely separate profile under a different user on my computer.

**Comment by anewuser** [comment]
@tumpio You may have to contact Mozilla about this. The latest versions went missing - https://addons.mozilla.org/addon/requestcontrol/versions/

**Comment by tumpio** [comment]
Some add-on review issue after 6 months from the release. Nice!

From 1.10 onward, I'm using tldjs library, and I haven't specially mentioned which version I'm using (its the latest 2.3.1). I'll release it to AMO, and add the note for it..

**Comment by krathalan** [comment]
Checked for updates just now and RC updated to 1.11.2 and everything seems to be back to normal. Thanks!
