### ISSUE TITLE
Support for literal strings in redirect

### ISSUE THREAD

**Issue by AeliusSaionji** [tumpio/requestcontrol#94]
I'm trying to create a redirect rule which starts like `{href}#cfg=%7B%22settings%22%3A`- the website in question accepts this as a delivery method for certain settings. Unfortunately it keeps getting expanded to an invalid URL like so `{href}#cfg={"settings":`.

Is there a way to prevent this from happening?

**Comment by anewuser** [comment]
Please post the full source and target URLs. You can change the domain to `example.com`  if you want privacy.

**Comment by AeliusSaionji** [comment]
Not necessary- the problem is clear. Parts of the URL are valid as an encoded string, but requestcontrol is expanding/decoding the string.

**Comment by anewuser** [comment]
Okay, since my help is not necessary, I'm unfollowing this issue.

**Comment by tumpio** [comment]
@AeliusSaionji  can you give me some steps to reproduce this? Tried your redirect url and it's working for me. It redirects me to `http://example.com/#cfg=%7B%22settings%22%3A`.

**Comment by AeliusSaionji** [comment]
I created a quick rule on a different PC like so
![image](https://user-images.githubusercontent.com/4342746/53661820-57762200-3c2f-11e9-9180-e4b4d0e3a143.png)

Result:
![image](https://user-images.githubusercontent.com/4342746/53661889-7f658580-3c2f-11e9-9b3a-c220c00f8afc.png)

**Comment by tumpio** [comment]
URL displayed in Firefox address bar is decoded. What output do you get if you copy/paste it for example.

**Comment by AeliusSaionji** [comment]
Hmm, then the issue seems to be that the site is redirecting from #cfg to a base url, and requestcontrol redirects it back. Infinite loop.

Not sure how to solve this.

**Comment by tumpio** [comment]
There are couple of options to create exclusions:
1 .Write the path pattern as such that is excludes the target redirect url.
2. Use the Excludes/Includes patterns in Extra URL Matchers
3. Create a white list rule for the target redirect url

**Comment by AeliusSaionji** [comment]
I don't think any of these options can work when I want to create a requestcontrol redirect from `{href}` to `{href}#data`, and the site itself autoredirects back to `{href}`.

**Comment by tumpio** [comment]
Oh. So you don't want to redirect again if it gets reverted back, but you still want to do the redirection once (even though its reverted)? This would require a way to exclude by origin, skip if origin is `{href}#data`

**Comment by AeliusSaionji** [comment]
Yeah I have given up on this because it's so niche and not that important and this is probably the worst way to do it, so no worries. 

> (even though its reverted)?

The running php or whatever interface receives the passed data as config options and then cleans up the url for you. For some reason the site doesn't use cookies.
